# Generated by `fm footman tools color` — do not edit by hand.
#
# Each curated tool's probed colour control: how footman forces it on and off.
# `tools.py` reads this for its forcing table; the docs read it for the support
# table. A tool obeys `env` (FORCE_COLOR/NO_COLOR), needs its own `flag`, or can
# force neither way (`none`); `unprobed` had no trigger.
#
# key -> (argv0, on, off, flag_on, flag_off, pre_verb)
_Row = tuple[str, str, str, tuple[str, ...], tuple[str, ...], bool]

COLOUR: dict[str, _Row] = {
    "basedpyright": ("basedpyright", "env", "env", (), (), False),
    "build": ("pyproject-build", "env", "env", (), (), False),
    "bun": ("bun", "env", "env", (), (), False),
    "cmake": ("cmake", "env", "env", (), (), False),
    "coverage": ("coverage", "none", "env", (), (), False),
    "cspell": ("cspell", "flag", "env", ("--color",), ("--no-color",), False),
    "djlint": ("djlint", "none", "env", (), (), False),
    "docker": ("docker", "none", "env", (), (), False),
    "eclint": ("eclint", "none", "env", (), (), False),
    "gh": ("gh", "env", "env", (), (), False),
    "git": (
        "git",
        "flag",
        "env",
        ("-c", "color.ui=always"),
        ("-c", "color.ui=never"),
        True,
    ),
    "git_changelog": ("git-changelog", "env", "env", (), (), False),
    "git_cliff": ("git-cliff", "env", "none", (), (), False),
    "markdownlint": ("markdownlint-cli2", "none", "env", (), (), False),
    "mkdocs": ("mkdocs", "none", "env", (), (), False),
    "mypy": ("mypy", "env", "env", (), (), False),
    "ninja": ("ninja", "env", "env", (), (), False),
    "prek": ("prek", "env", "env", (), (), False),
    "pytest": ("pytest", "env", "env", (), (), False),
    "python": ("python", "none", "env", (), (), False),
    "ruff": ("ruff", "env", "env", (), (), False),
    "ruff_format": ("ruff", "env", "env", (), (), False),
    "twine": ("twine", "env", "none", (), (), False),
    "ty": ("ty", "env", "env", (), (), False),
    "uv": ("uv", "env", "env", (), (), False),
    "zensical": ("zensical", "none", "env", (), (), False),
}
