# Generated by `fm footman tools color` — do not edit by hand.
#
# Each curated tool's probed colour control: how footman forces it on and off.
# `tools.py` reads this for its forcing table; the docs read it for the support
# table. A tool obeys `env` (FORCE_COLOR/NO_COLOR), needs its own `flag`, or can
# force neither way (`none`); `unprobed` had no trigger.
#
# key -> (argv0, on, off, flag_on, flag_off, pre_verb)
_Row = tuple[str, str, str, tuple[str, ...], tuple[str, ...], bool]

COLOUR: dict[str, _Row] = {
    "basedpyright": ("basedpyright", "unprobed", "unprobed", (), (), False),
    "cmake": ("cmake", "unprobed", "unprobed", (), (), False),
    "coverage": ("coverage", "unprobed", "unprobed", (), (), False),
    "docker": ("docker", "unprobed", "unprobed", (), (), False),
    "gh": ("gh", "unprobed", "unprobed", (), (), False),
    "git": (
        "git",
        "flag",
        "env",
        ("-c", "color.ui=always"),
        ("-c", "color.ui=never"),
        True,
    ),
    "mkdocs": ("mkdocs", "unprobed", "unprobed", (), (), False),
    "ninja": ("ninja", "unprobed", "unprobed", (), (), False),
    "pytest": ("pytest", "env", "env", (), (), False),
    "python": ("python", "unprobed", "unprobed", (), (), False),
    "ruff": ("ruff", "env", "env", (), (), False),
    "ruff_format": ("ruff", "env", "env", (), (), False),
    "uv": ("uv", "unprobed", "unprobed", (), (), False),
    "zensical": ("zensical", "unprobed", "unprobed", (), (), False),
}
