"""Shell completion installers — `fm --install-completion bash|zsh|fish|pwsh`.

Each generated script calls `<prog> --complete -- WORD...` on TAB: the
stdlib-only hot path that answers from the cached manifest without importing
footman or the user's code. Scripts are generated per brand, so a custom CLI
(`acme --install-completion zsh`) installs completion for *its* name.

Install layout (all idempotent — running twice changes nothing):

- bash: script in `$XDG_DATA_HOME/<prog>/completion.bash`, one guarded
  `source` line appended to `~/.bashrc`.
- zsh: script in `$XDG_DATA_HOME/<prog>/completion.zsh`, one guarded
  `source` line appended to `~/.zshrc`.
- fish: `~/.config/fish/completions/<prog>.fish` — fish auto-loads the
  directory; no rc editing at all.
- pwsh: script in `$XDG_DATA_HOME/<prog>/completion.ps1`, one guarded
  dot-source line appended to the profile PowerShell itself reports
  (`$PROFILE`); works for PowerShell 7+ and Windows PowerShell 5.
- nushell: script in `$XDG_DATA_HOME/<prog>/completion.nu`, one guarded
  `source` line appended to the config nushell itself reports
  (`$nu.config-path`). The hook *wraps* any existing external completer
  (carapace, fish-based, …) instead of replacing it.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

SHELLS = ("bash", "zsh", "fish", "pwsh", "nushell")


class InstallError(Exception):
    """Completion could not be installed; the message says why."""


_BASH = """\
# {prog} shell completion (generated by `{prog} --install-completion bash`)
_{fn}_complete() {{
    # An index loop, not "${{COMP_WORDS[@]:1:COMP_CWORD}}": the quoted array
    # slice collapses to a single word on macOS's bash 3.2.
    local -a words=()
    local i
    for ((i = 1; i <= COMP_CWORD; i++)); do
        words[i - 1]=${{COMP_WORDS[i]}}
    done
    # Read one candidate per line and %q-quote each, so a candidate like *.md or
    # "a b" is inserted literally — never pathname-expanded the way a
    # split-and-glob command substitution into the array would. bash has no
    # description column, so drop anything after the first tab.
    COMPREPLY=()
    local line
    while IFS= read -r line; do
        line=${{line%%$'\\t'*}}
        printf -v line '%q' "$line"
        COMPREPLY+=("$line")
    done < <({prog} --complete -- "${{words[@]}}" 2>/dev/null)
}}
complete -o default -F _{fn}_complete {prog}
"""

_ZSH = """\
# {prog} shell completion (generated by `{prog} --install-completion zsh`)
if ! typeset -f compdef >/dev/null 2>&1; then
    # -u: skip compaudit's interactive prompt — this fallback only fires when
    # nothing else initialised completion (fresh HOMEs, non-interactive use),
    # exactly where a prompt would wedge instead of asking.
    autoload -Uz compinit && compinit -u
fi
_{fn}_complete() {{
    local -a items
    local raw line
    # (@) + quotes keeps the empty current word when the cursor follows a
    # space — unquoted expansion would drop it.
    raw="$({prog} --complete -- "${{(@)words[2,CURRENT]}}" 2>/dev/null)"
    for line in ${{(f)raw}}; do
        # `value:description` feeds _describe, which right-aligns the
        # descriptions into a column and honours the user's completion colours
        # (list-colors / descriptions format). A tab-less line — an option or a
        # choice value — is a bare value with no description.
        if [[ $line == *$'\\t'* ]]; then
            items+=("${{line%%$'\\t'*}}:${{line#*$'\\t'}}")
        else
            items+=("$line")
        fi
    done
    (( ${{#items}} )) && _describe -t {fn} '{prog}' items
}}
compdef _{fn}_complete {prog}
"""

_FISH = """\
# {prog} shell completion (generated by `{prog} --install-completion fish`)
function __{fn}_complete
    set -l words (commandline -opc) (commandline -ct)
    {prog} --complete -- $words[2..-1] 2>/dev/null
end
complete -c {prog} -f -a '(__{fn}_complete)'
"""

_PWSH = """\
# {prog} shell completion (generated by `{prog} --install-completion pwsh`)
Register-ArgumentCompleter -Native -CommandName {prog} -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $words = @($commandAst.CommandElements |
        Select-Object -Skip 1 | ForEach-Object {{ $_.ToString() }})
    # WinPS 5.1 and pwsh 7.0-7.2 silently drop an empty-string arg to a native
    # command, so a trailing '' partial can't be passed directly. Flag the empty
    # position instead; the resolver appends the '' itself.
    $empty = if ($wordToComplete -eq '') {{ '--empty-partial' }} else {{ $null }}
    & {prog} --complete $empty -- @words 2>$null | ForEach-Object {{
        # `value` or `value<tab>description`: the tail becomes the tooltip.
        $parts = $_ -split "`t", 2
        $val = $parts[0]
        $tip = if ($parts.Count -gt 1) {{ $parts[1] }} else {{ $val }}
        [System.Management.Automation.CompletionResult]::new(
            $val, $val, 'ParameterValue', $tip)
    }}
}}
"""

_NU = """\
# {prog} shell completion (generated by `{prog} --install-completion nushell`)
# Wraps any existing external completer (carapace, …) instead of replacing it.
let __{fn}_prev = ($env.config.completions?.external?.completer? | default null)
$env.config.completions.external.enable = true
$env.config.completions.external.completer = {{|spans|
    if $spans.0 == "{prog}" {{
        # Split `value<tab>description` into a record so nushell renders the
        # description column; a tab-less line (option/choice) is a bare value.
        ^{prog} --complete -- ...($spans | skip 1) | lines | each {{|l|
            let p = ($l | split row (char tab))
            if ($p | length) > 1 {{
                {{value: $p.0, description: $p.1}}
            }} else {{
                {{value: $p.0}}
            }}
        }}
    }} else if $__{fn}_prev != null {{
        do $__{fn}_prev $spans
    }} else {{
        null
    }}
}}
"""

_TEMPLATES = {"bash": _BASH, "zsh": _ZSH, "fish": _FISH, "pwsh": _PWSH, "nushell": _NU}


def script_for(shell: str, prog: str) -> str:
    """The completion script for *shell*, branded for *prog*."""
    fn = prog.replace("-", "_")
    return _TEMPLATES[shell].format(prog=prog, fn=fn)


def _data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")


def _sniff_encoding(raw: bytes) -> tuple[str, str]:
    """(decode, append) encodings for rc bytes, sniffed from any leading BOM.

    The append encoder is BOM-free (`utf-8`, `utf-16-le`/`-be`) so we never
    inject a second BOM mid-file. With no BOM, prefer UTF-8 and fall back to
    latin-1, which round-trips arbitrary bytes rather than raising.
    """
    if raw.startswith(b"\xef\xbb\xbf"):
        return "utf-8-sig", "utf-8"
    if raw.startswith(b"\xff\xfe"):
        return "utf-16", "utf-16-le"
    if raw.startswith(b"\xfe\xff"):
        return "utf-16", "utf-16-be"
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError:
        return "latin-1", "latin-1"
    return "utf-8", "utf-8"


def _append_once(rc: Path, line: str) -> bool:
    """Append *line* to *rc* unless present; True if the file changed.

    rc files carry whatever encoding the shell wrote — a Windows PowerShell 5
    `$PROFILE` is UTF-16 with a BOM. Read the bytes, sniff the BOM, and append
    in the matching (BOM-free) encoding, so a UTF-16 profile is neither crashed
    on read nor corrupted by a UTF-8 tail. A residual write failure becomes an
    `InstallError` naming the exact line to add, routed to the existing exit-2
    path instead of a raw traceback.
    """
    try:
        raw = rc.read_bytes() if rc.exists() else b""
    except OSError as exc:
        raise InstallError(_manual_hint(rc, line, exc)) from exc

    read_enc, append_enc = _sniff_encoding(raw)
    existing = raw.decode(read_enc, errors="replace")
    if line in existing:
        return False

    joiner = "" if existing.endswith("\n") or not existing else "\n"
    payload = f"{joiner}{line}\n".encode(append_enc)
    try:
        rc.parent.mkdir(parents=True, exist_ok=True)
        with rc.open("ab") as fh:  # binary: no TextIOWrapper BOM injection
            fh.write(payload)
    except OSError as exc:
        raise InstallError(_manual_hint(rc, line, exc)) from exc
    return True


def _manual_hint(rc: Path, line: str, exc: Exception) -> str:
    return f"could not update {rc} ({exc}) — add this line yourself: {line}"


def _zsh_rc() -> Path:
    """The `.zshrc` zsh actually reads — under `$ZDOTDIR` when set (D11)."""
    zdotdir = os.environ.get("ZDOTDIR")
    base = Path(zdotdir) if zdotdir else Path.home()
    return base / ".zshrc"


def _bash_rcs() -> list[Path]:
    """The rc files bash actually reads for completion to activate (D11).

    `.bashrc` covers interactive non-login shells. On macOS, Terminal opens
    *login* shells, which read a login profile (`.bash_profile`/`.bash_login`/
    `.profile`) and not `.bashrc` — so append there too, to the first existing
    one, creating `.bash_profile` only when none exists (never shadowing an
    existing `.profile`).
    """
    home = Path.home()
    rcs = [home / ".bashrc"]
    if sys.platform == "darwin":
        logins = [home / ".bash_profile", home / ".bash_login", home / ".profile"]
        existing = next((p for p in logins if p.exists()), None)
        rcs.append(existing or home / ".bash_profile")
    return rcs


_PROC_NAMES = {
    "bash": "bash",
    "zsh": "zsh",
    "fish": "fish",
    "nu": "nushell",
    "pwsh": "pwsh",
    "powershell": "pwsh",
}


def detect_shell() -> str | None:
    """Best-effort, zero-dependency detection of the invoking shell.

    Walks the parent-process tree (the immediate parent is often `uv`, not
    the shell) looking for a known shell name — what shellingham does for
    typer, without the dependency. Windows has no `ps`, so the PowerShell
    tell there is the `PSModulePath` variable it exports to children. Falls
    back to the login shell in `$SHELL`; returns `None` when nothing is
    confidently recognised.
    """
    if os.name == "nt":
        # PSModulePath is machine-level environment on modern Windows, so
        # this over-claims from cmd.exe — acceptable, because cmd has no
        # completion mechanism and a PowerShell install is the most useful
        # answer on that box. (Real spelling kept; Windows env lookup is
        # case-insensitive anyway.)
        return "pwsh" if os.environ.get("PSModulePath") else None  # noqa: SIM112
    return _detect_posix()


def _detect_posix() -> str | None:
    pid = os.getppid()
    for _ in range(10):
        if pid <= 1:
            break
        try:
            out = subprocess.run(
                ["ps", "-p", str(pid), "-o", "ppid=,comm="],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            break
        line = out.stdout.strip()
        if out.returncode != 0 or not line:
            break
        ppid, _, comm = line.partition(" ")
        # A login shell reports as "-zsh"; comm may be a full path.
        name = Path(comm.strip()).name.lstrip("-")
        if name in _PROC_NAMES:
            return _PROC_NAMES[name]
        try:
            pid = int(ppid)
        except ValueError:
            break
    login = Path(os.environ.get("SHELL", "")).name
    return _PROC_NAMES.get(login)


def _ask_shell(candidates: tuple[str, ...], args: list[str]) -> str | None:
    """Run the first available *candidates* binary and return its stdout."""
    for exe in candidates:
        binary = shutil.which(exe)
        if binary is None:
            continue
        try:
            out = subprocess.run(
                [binary, *args], capture_output=True, text=True, timeout=30
            )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    return None


def _pwsh_profiles() -> list[Path]:
    """Every distinct `$PROFILE` among the PowerShells on PATH.

    PowerShell 7 (`pwsh`) and Windows PowerShell (`powershell`) keep
    *different* profile files; on a machine with both, completion should work
    in whichever one the user opens — so the installer targets them all.
    """
    profiles: list[Path] = []
    for exe in ("pwsh", "powershell"):
        path = _ask_shell((exe,), ["-NoProfile", "-Command", "$PROFILE"])
        if path is not None and Path(path) not in profiles:
            profiles.append(Path(path))
    if not profiles:
        raise InstallError(
            "pwsh (or powershell) not found on PATH — install PowerShell first"
        )
    return profiles


def _nu_config_path() -> Path:
    """The config file nushell itself reports (`$nu.config-path`)."""
    path = _ask_shell(("nu",), ["-c", "$nu.config-path"])
    if path is None:
        raise InstallError("nu not found on PATH — install nushell first")
    return Path(path)


def install(shell: str, prog: str) -> list[str]:
    """Install completion for *shell*; return the lines to tell the user.

    Raises `KeyError` for an unsupported shell and `InstallError` when the
    shell itself is missing — the caller owns the taught error (it knows the
    brand).
    """
    script = script_for(shell, prog)

    if shell == "fish":
        target = _config_home() / "fish" / "completions" / f"{prog}.fish"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script, encoding="utf-8")
        return [
            f"installed {target}",
            "fish picks it up automatically — start a new shell and TAB away.",
        ]

    suffix = {"pwsh": "ps1", "nushell": "nu"}.get(shell, shell)
    target = _data_home() / prog / f"completion.{suffix}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    if shell == "pwsh":
        # The hook runs on PowerShell 5+ unchanged, so it goes into every
        # PowerShell profile present — both shells complete, whoever answers.
        hooks = [(rc, f'. "{target}"') for rc in _pwsh_profiles()]
    elif shell == "nushell":
        hooks = [(_nu_config_path(), f'source "{target}"')]
    elif shell == "zsh":
        hooks = [(_zsh_rc(), f"source {target}")]
    else:  # bash
        hooks = [(rc, f"source {target}") for rc in _bash_rcs()]
    lines = [f"installed {target}"]
    for rc, line in hooks:
        if _append_once(rc, line):
            lines.append(f"added `{line}` to {rc}")
        else:
            lines.append(f"{rc} already sources it")
    lines.append("restart your shell (or source the rc file) and TAB away.")
    return lines
