"""Shell completion installers — `fm --install-completion bash|zsh|fish`.

Each generated script calls `<prog> --complete -- WORD...` on TAB: the
stdlib-only hot path that answers from the cached manifest without importing
footman or the user's code. Scripts are generated per brand, so a custom CLI
(`acme --install-completion zsh`) installs completion for *its* name.

Install layout (all idempotent — running twice changes nothing):

- bash: script in `$XDG_DATA_HOME/<prog>/completion.bash`, one guarded
  `source` line appended to `~/.bashrc`.
- zsh: script in `$XDG_DATA_HOME/<prog>/completion.zsh`, one guarded
  `source` line appended to `~/.zshrc`.
- fish: `~/.config/fish/completions/<prog>.fish` — fish auto-loads the
  directory; no rc editing at all.
"""

from __future__ import annotations

import os
from pathlib import Path

SHELLS = ("bash", "zsh", "fish")

_BASH = """\
# {prog} shell completion (generated by `{prog} --install-completion bash`)
_{fn}_complete() {{
    local IFS=$'\\n'
    # An index loop, not "${{COMP_WORDS[@]:1:COMP_CWORD}}": the quoted array
    # slice collapses to a single word on macOS's bash 3.2.
    local -a words=()
    local i
    for ((i = 1; i <= COMP_CWORD; i++)); do
        words[i - 1]=${{COMP_WORDS[i]}}
    done
    COMPREPLY=($({prog} --complete -- "${{words[@]}}" 2>/dev/null))
}}
complete -o default -F _{fn}_complete {prog}
"""

_ZSH = """\
# {prog} shell completion (generated by `{prog} --install-completion zsh`)
if ! typeset -f compdef >/dev/null 2>&1; then
    autoload -Uz compinit && compinit
fi
_{fn}_complete() {{
    local -a completions
    local raw
    # (@) + quotes keeps the empty current word when the cursor follows a
    # space — unquoted expansion would drop it.
    raw="$({prog} --complete -- "${{(@)words[2,CURRENT]}}" 2>/dev/null)"
    completions=(${{(f)raw}})
    (( ${{#completions}} )) && compadd -a completions
}}
compdef _{fn}_complete {prog}
"""

_FISH = """\
# {prog} shell completion (generated by `{prog} --install-completion fish`)
function __{fn}_complete
    set -l words (commandline -opc) (commandline -ct)
    {prog} --complete -- $words[2..-1] 2>/dev/null
end
complete -c {prog} -f -a '(__{fn}_complete)'
"""

_TEMPLATES = {"bash": _BASH, "zsh": _ZSH, "fish": _FISH}


def script_for(shell: str, prog: str) -> str:
    """The completion script for *shell*, branded for *prog*."""
    fn = prog.replace("-", "_")
    return _TEMPLATES[shell].format(prog=prog, fn=fn)


def _data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")


def _append_once(rc: Path, line: str) -> bool:
    """Append *line* to *rc* unless present; True if the file changed."""
    existing = rc.read_text(encoding="utf-8") if rc.exists() else ""
    if line in existing:
        return False
    rc.parent.mkdir(parents=True, exist_ok=True)
    joiner = "" if existing.endswith("\n") or not existing else "\n"
    with rc.open("a", encoding="utf-8") as fh:
        fh.write(f"{joiner}{line}\n")
    return True


def install(shell: str, prog: str) -> list[str]:
    """Install completion for *shell*; return the lines to tell the user.

    Raises `KeyError` for an unsupported shell — the caller owns the taught
    error (it knows the brand).
    """
    script = script_for(shell, prog)

    if shell == "fish":
        target = _config_home() / "fish" / "completions" / f"{prog}.fish"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script, encoding="utf-8")
        return [
            f"installed {target}",
            "fish picks it up automatically — start a new shell and TAB away.",
        ]

    target = _data_home() / prog / f"completion.{shell}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    rc = Path.home() / f".{shell}rc"
    line = f"source {target}"
    changed = _append_once(rc, line)
    note = f"added `{line}` to {rc}" if changed else f"{rc} already sources it"
    return [
        f"installed {target}",
        note,
        "restart your shell (or source the rc file) and TAB away.",
    ]
