"""Shell completion installers — `fm --install-completion bash|zsh|fish|pwsh`.

Each generated script calls `<prog> --complete -- WORD...` on TAB: the
stdlib-only hot path that answers from the cached manifest without importing
footman or the user's code. Scripts are generated per brand, so a custom CLI
(`acme --install-completion zsh`) installs completion for *its* name.

Install layout (all idempotent — running twice changes nothing):

- bash: script in `$XDG_DATA_HOME/<prog>/completion.bash`, one guarded
  `source` line appended to `~/.bashrc`.
- zsh: script in `$XDG_DATA_HOME/<prog>/completion.zsh`, one guarded
  `source` line appended to `~/.zshrc`.
- fish: `~/.config/fish/completions/<prog>.fish` — fish auto-loads the
  directory; no rc editing at all.
- pwsh: script in `$XDG_DATA_HOME/<prog>/completion.ps1`, one guarded
  dot-source line appended to the profile PowerShell itself reports
  (`$PROFILE`); works for PowerShell 7+ and Windows PowerShell 5.
- nushell: script in `$XDG_DATA_HOME/<prog>/completion.nu`, one guarded
  `source` line appended to the config nushell itself reports
  (`$nu.config-path`). The hook *wraps* any existing external completer
  (carapace, fish-based, …) instead of replacing it.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

SHELLS = ("bash", "zsh", "fish", "pwsh", "nushell")


class InstallError(Exception):
    """Completion could not be installed; the message says why."""


_BASH = """\
# {prog} shell completion (generated by `{prog} --install-completion bash`)
_{fn}_complete() {{
    local IFS=$'\\n'
    # An index loop, not "${{COMP_WORDS[@]:1:COMP_CWORD}}": the quoted array
    # slice collapses to a single word on macOS's bash 3.2.
    local -a words=()
    local i
    for ((i = 1; i <= COMP_CWORD; i++)); do
        words[i - 1]=${{COMP_WORDS[i]}}
    done
    COMPREPLY=($({prog} --complete -- "${{words[@]}}" 2>/dev/null))
}}
complete -o default -F _{fn}_complete {prog}
"""

_ZSH = """\
# {prog} shell completion (generated by `{prog} --install-completion zsh`)
if ! typeset -f compdef >/dev/null 2>&1; then
    # -u: skip compaudit's interactive prompt — this fallback only fires when
    # nothing else initialised completion (fresh HOMEs, non-interactive use),
    # exactly where a prompt would wedge instead of asking.
    autoload -Uz compinit && compinit -u
fi
_{fn}_complete() {{
    local -a completions
    local raw
    # (@) + quotes keeps the empty current word when the cursor follows a
    # space — unquoted expansion would drop it.
    raw="$({prog} --complete -- "${{(@)words[2,CURRENT]}}" 2>/dev/null)"
    completions=(${{(f)raw}})
    (( ${{#completions}} )) && compadd -a completions
}}
compdef _{fn}_complete {prog}
"""

_FISH = """\
# {prog} shell completion (generated by `{prog} --install-completion fish`)
function __{fn}_complete
    set -l words (commandline -opc) (commandline -ct)
    {prog} --complete -- $words[2..-1] 2>/dev/null
end
complete -c {prog} -f -a '(__{fn}_complete)'
"""

_PWSH = """\
# {prog} shell completion (generated by `{prog} --install-completion pwsh`)
Register-ArgumentCompleter -Native -CommandName {prog} -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $words = @($commandAst.CommandElements |
        Select-Object -Skip 1 | ForEach-Object {{ $_.ToString() }})
    # WinPS 5.1 and pwsh 7.0-7.2 silently drop an empty-string arg to a native
    # command, so a trailing '' partial can't be passed directly. Flag the empty
    # position instead; the resolver appends the '' itself.
    $empty = if ($wordToComplete -eq '') {{ '--empty-partial' }} else {{ $null }}
    & {prog} --complete $empty -- @words 2>$null | ForEach-Object {{
        [System.Management.Automation.CompletionResult]::new(
            $_, $_, 'ParameterValue', $_)
    }}
}}
"""

_NU = """\
# {prog} shell completion (generated by `{prog} --install-completion nushell`)
# Wraps any existing external completer (carapace, …) instead of replacing it.
let __{fn}_prev = ($env.config.completions?.external?.completer? | default null)
$env.config.completions.external.enable = true
$env.config.completions.external.completer = {{|spans|
    if $spans.0 == "{prog}" {{
        ^{prog} --complete -- ...($spans | skip 1) | lines
    }} else if $__{fn}_prev != null {{
        do $__{fn}_prev $spans
    }} else {{
        null
    }}
}}
"""

_TEMPLATES = {"bash": _BASH, "zsh": _ZSH, "fish": _FISH, "pwsh": _PWSH, "nushell": _NU}


def script_for(shell: str, prog: str) -> str:
    """The completion script for *shell*, branded for *prog*."""
    fn = prog.replace("-", "_")
    return _TEMPLATES[shell].format(prog=prog, fn=fn)


def _data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")


def _append_once(rc: Path, line: str) -> bool:
    """Append *line* to *rc* unless present; True if the file changed."""
    existing = rc.read_text(encoding="utf-8") if rc.exists() else ""
    if line in existing:
        return False
    rc.parent.mkdir(parents=True, exist_ok=True)
    joiner = "" if existing.endswith("\n") or not existing else "\n"
    with rc.open("a", encoding="utf-8") as fh:
        fh.write(f"{joiner}{line}\n")
    return True


_PROC_NAMES = {
    "bash": "bash",
    "zsh": "zsh",
    "fish": "fish",
    "nu": "nushell",
    "pwsh": "pwsh",
    "powershell": "pwsh",
}


def detect_shell() -> str | None:
    """Best-effort, zero-dependency detection of the invoking shell.

    Walks the parent-process tree (the immediate parent is often `uv`, not
    the shell) looking for a known shell name — what shellingham does for
    typer, without the dependency. Windows has no `ps`, so the PowerShell
    tell there is the `PSModulePath` variable it exports to children. Falls
    back to the login shell in `$SHELL`; returns `None` when nothing is
    confidently recognised.
    """
    if os.name == "nt":
        # PSModulePath is machine-level environment on modern Windows, so
        # this over-claims from cmd.exe — acceptable, because cmd has no
        # completion mechanism and a PowerShell install is the most useful
        # answer on that box. (Real spelling kept; Windows env lookup is
        # case-insensitive anyway.)
        return "pwsh" if os.environ.get("PSModulePath") else None  # noqa: SIM112
    return _detect_posix()


def _detect_posix() -> str | None:
    pid = os.getppid()
    for _ in range(10):
        if pid <= 1:
            break
        try:
            out = subprocess.run(
                ["ps", "-p", str(pid), "-o", "ppid=,comm="],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            break
        line = out.stdout.strip()
        if out.returncode != 0 or not line:
            break
        ppid, _, comm = line.partition(" ")
        # A login shell reports as "-zsh"; comm may be a full path.
        name = Path(comm.strip()).name.lstrip("-")
        if name in _PROC_NAMES:
            return _PROC_NAMES[name]
        try:
            pid = int(ppid)
        except ValueError:
            break
    login = Path(os.environ.get("SHELL", "")).name
    return _PROC_NAMES.get(login)


def _ask_shell(candidates: tuple[str, ...], args: list[str]) -> str | None:
    """Run the first available *candidates* binary and return its stdout."""
    for exe in candidates:
        binary = shutil.which(exe)
        if binary is None:
            continue
        try:
            out = subprocess.run(
                [binary, *args], capture_output=True, text=True, timeout=30
            )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.strip()
    return None


def _pwsh_profiles() -> list[Path]:
    """Every distinct `$PROFILE` among the PowerShells on PATH.

    PowerShell 7 (`pwsh`) and Windows PowerShell (`powershell`) keep
    *different* profile files; on a machine with both, completion should work
    in whichever one the user opens — so the installer targets them all.
    """
    profiles: list[Path] = []
    for exe in ("pwsh", "powershell"):
        path = _ask_shell((exe,), ["-NoProfile", "-Command", "$PROFILE"])
        if path is not None and Path(path) not in profiles:
            profiles.append(Path(path))
    if not profiles:
        raise InstallError(
            "pwsh (or powershell) not found on PATH — install PowerShell first"
        )
    return profiles


def _nu_config_path() -> Path:
    """The config file nushell itself reports (`$nu.config-path`)."""
    path = _ask_shell(("nu",), ["-c", "$nu.config-path"])
    if path is None:
        raise InstallError("nu not found on PATH — install nushell first")
    return Path(path)


def install(shell: str, prog: str) -> list[str]:
    """Install completion for *shell*; return the lines to tell the user.

    Raises `KeyError` for an unsupported shell and `InstallError` when the
    shell itself is missing — the caller owns the taught error (it knows the
    brand).
    """
    script = script_for(shell, prog)

    if shell == "fish":
        target = _config_home() / "fish" / "completions" / f"{prog}.fish"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script, encoding="utf-8")
        return [
            f"installed {target}",
            "fish picks it up automatically — start a new shell and TAB away.",
        ]

    suffix = {"pwsh": "ps1", "nushell": "nu"}.get(shell, shell)
    target = _data_home() / prog / f"completion.{suffix}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    if shell == "pwsh":
        # The hook runs on PowerShell 5+ unchanged, so it goes into every
        # PowerShell profile present — both shells complete, whoever answers.
        hooks = [(rc, f'. "{target}"') for rc in _pwsh_profiles()]
    elif shell == "nushell":
        hooks = [(_nu_config_path(), f'source "{target}"')]
    else:
        hooks = [(Path.home() / f".{shell}rc", f"source {target}")]
    lines = [f"installed {target}"]
    for rc, line in hooks:
        if _append_once(rc, line):
            lines.append(f"added `{line}` to {rc}")
        else:
            lines.append(f"{rc} already sources it")
    lines.append("restart your shell (or source the rc file) and TAB away.")
    return lines
