"""Render a `ToolSpec` as the stub a type checker reads.

The bridge in `tools.py` translates keyword arguments mechanically and will
happily pass a flag no stub has heard of — that is what keeps it from going
stale. The stub is the other half: it tells an IDE what the installed tool
*currently* accepts, so the flags complete and their help text is right
there on hover, without importing the tool to find out.

Three things make a generated stub better than a hand-written one:

* it says what the tool says, because it was read from the tool;
* it can be regenerated, so drift is a diff rather than an archaeology
  exercise (`fm footman tools audit` is that diff, run in CI);
* it can carry the tool's own prose per flag, including the one fact a
  bridge can never infer — how *this* tool spells "off".

Every generated verb still ends in `**flags: Any`, so a stub that lags the
installed tool degrades a hint and never a run.
"""

from __future__ import annotations

import re
import textwrap
from collections.abc import Iterable

from footman._toolspec import Option, ToolSpec, Verb

_HEADER = """\
# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from {name} {version} on {platform}. In-process: {in_process}.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
{imports}
"""


def render(
    spec: ToolSpec,
    *,
    platform: str = "",
    class_name: str = "",
    in_process: str = "",
) -> str:
    """The full text of `_stubs/<tool>.pyi` for *spec*."""
    root = class_name or _class_name(spec.name)
    tree = _tree(spec.verbs)
    classes = _classes(tree, root)
    header = _HEADER.format(
        name=spec.name,
        version=spec.version or "an unpinned version",
        platform=platform or "this machine",
        in_process=in_process or ("available" if spec.in_process else "no"),
        imports=_imports("\n".join(classes)),
    )
    return "\n".join([header, *classes])


def _imports(body: str) -> str:
    """Just the imports the body uses — an unused one fails the lint gate."""
    typing = ["Any"] + (["Literal"] if "Literal[" in body else [])
    aliases = ("_Flag", "_Value", "_ValuedFlag")
    # `Result` is always the return type of every generated call, so always imported.
    names = ["Result", "Tool"] + [n for n in aliases if re.search(rf"\b{n}\b", body)]
    lines = []
    if "Sequence[" in body:
        lines.append("from collections.abc import Sequence")
    lines.append(f"from typing import {', '.join(typing)}")
    lines.append("")
    lines.append(f"from footman.tools import {', '.join(names)}")
    return "\n".join(lines)


def _class_name(name: str) -> str:
    """`markdownlint-cli2` → `Markdownlint`. Public: these classes are the
    typed surface of `tools.<name>`, used (only in type position — they are
    stub-only, never imported at run time) as if they were public."""
    return "".join(part.title() for part in name.replace("-", "_").split("_"))


def _tree(verbs: Iterable[Verb]) -> dict[str, object]:
    """Nest dotted verb names: `compose.up` hangs under `compose`."""
    tree: dict[str, object] = {}
    for verb in verbs:
        node = tree
        parts = verb.name.split(".") if verb.name else []
        for part in parts[:-1]:
            child = node.setdefault(part, {})
            node = child if isinstance(child, dict) else {}
        node[parts[-1] if parts else ""] = verb
    return tree


def _classes(tree: dict[str, object], name: str) -> list[str]:
    """This class, plus one for every subgroup below it, deepest first."""
    out: list[str] = []
    body: list[str] = []
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, dict):
            child = f"{name}{key.title().replace('_', '')}"
            out.extend(_classes(node, child))
            body.append(f"    {key}: {child}")
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, Verb):
            body.append(_method(node, key))
    # A tool with subcommands gets a typed `.flags()` returning its own class,
    # so a globals-before-verb chain stays checked. The root verb's options
    # are the typed globals (git's `--git-dir`, docker's `--host`); a tool
    # with none still gets the self-returning override, for the chaining.
    # (footman run-control rides the inherited `.opts()`, typed on Tool.)
    if _has_subcommands(tree):
        root = tree.get("")
        globals_ = root.options if isinstance(root, Verb) else ()
        body.append(_flags_method(globals_, name))
    out.append(f"class {name}(Tool):\n" + ("\n".join(body) or "    ..."))
    return out


def _has_subcommands(tree: dict[str, object]) -> bool:
    """Whether this class has verbs to precede — the only case `.flags()`
    means anything (a global belongs *before* a subcommand)."""
    return any(key != "" for key in tree)


def _flags_method(options: tuple[Option, ...], class_name: str) -> str:
    """The typed `flags()` for a tool's global options — returns the tool,
    so `tools.docker.flags(host=…).compose.up(…)` stays checked. With no
    globals it is still declared, so the return type carries the chain.
    (footman run-control — nofail/capture/… — goes on the inherited `.opts()`.)"""
    lines = ["    def flags(", "        self,"]
    typed = _unique(options)
    if typed:  # a `*` separator with only `**flags` after it is a syntax error
        lines.append("        *,")
        for option in typed:
            lines.append(f"        {_safe(option.name)}: {_annotation(option)} = ...,")
    lines.append("        **flags: Any,")
    lines.append(f"    ) -> {class_name}:")
    lines.append('        """Bind tool-level global options before the subcommand.')
    lines.append("")
    lines.append("        `tools.docker.flags(host=...)` puts a tool's own")
    lines.append('        options ahead of the verb, where they belong."""')
    lines.append("        ...")
    return "\n".join(lines)


def _method(verb: Verb, key: str) -> str:
    """One verb as a stub method — or `__call__` for a tool's own flags.

    footman run-control (nofail/capture/title/in_process) lives on the inherited
    `.opts()`, never the call, so a call signature is pure flags — which also
    means an option literally named `capture` (pytest's) types through here."""
    name = key or "__call__"
    override = "  # type: ignore[override]" if name == "__call__" else ""
    header = f"    def {name}({override}" if override else f"    def {name}("
    positional = _positional_lines(verb)
    options = _unique(verb.options)
    # A bare `*,` must be followed by a keyword-only parameter; when the only
    # thing after it would be `**flags`, drop it — `def f(self, **flags)` already
    # forbids a positional. (Previously the nofail/in_process params backfilled
    # the `*,`; those moved to `.opts()`.)
    if positional == ["        *,"] and not options:
        positional = []
    lines = [header, "        self,", *positional]
    for option in options:
        lines.append(f"        {_safe(option.name)}: {_annotation(option)} = ...,")
    lines.append("        **flags: Any,")
    lines.append("    ) -> Result:")
    doc = _docstring(verb)
    if doc:
        lines.append(doc)
    lines.append("        ...")
    return "\n".join(lines)


def _positional_lines(verb: Verb) -> list[str]:
    """The positional part of a verb's signature, from its usage shape.

    `"none"` → keyword-only (`*,`), so a stray positional is a type error;
    `"required"` → a positional-only leading argument, so passing it by
    keyword is one too; `"any"` → `*args`, the conservative default that
    forbids nothing.
    """
    if verb.positional == "none":
        return ["        *,"]
    if verb.positional == "required":
        lead = _safe(verb.lead) if verb.lead else "arg"
        # If the leading positional's name also names an option, the two
        # would collide into one parameter. Can't spell both, so don't
        # constrain: fall back to `*args`.
        if lead in {_safe(o.name) for o in verb.options}:
            return ["        *args: str,"]
        return [f"        {lead}: str,", "        /,", "        *args: str,"]
    return ["        *args: str,"]


# The method's own structural parameters. An option named the same (git
# rev-parse has `--flags`) would be a duplicate parameter — it still works,
# swallowed by `**flags` at type-check and `**kwargs` at run time, just not
# typed. `nofail`/`in_process` are no longer here — they moved to `.opts()`, so
# a tool that really has a `--nofail` flag now types through the call.
_RESERVED = frozenset({"self", "args", "flags"})


def _unique(options: tuple[Option, ...]) -> list[Option]:
    """One parameter per keyword — a repeat would be a syntax error, and a
    name that clashes with a fixed parameter is dropped to the catch-all."""
    seen: dict[str, Option] = {}
    for option in options:
        safe = _safe(option.name)
        if safe not in _RESERVED:
            seen.setdefault(safe, option)
    return list(seen.values())


def _safe(name: str) -> str:
    """A flag whose name is a Python keyword takes footman's trailing `_`."""
    import keyword

    return f"{name}_" if keyword.iskeyword(name) else name


def _esc(text: str) -> str:
    r"""Double every backslash: a help string like mypy's `--exclude '\.py$'`
    must land as a literal in the generated docstring, not an invalid `\.`
    escape sequence that a compiler warns on."""
    return text.replace("\\", "\\\\")


def _annotation(option: Option) -> str:
    """The stub's declared type for one option.

    Deliberately wide, because the stub's contract is to suggest and never
    to forbid. `_Value` takes a sequence as well as a scalar for *every*
    option, since the bridge repeats a flag for each item and whether the
    tool accepts repetition is the tool's business, not the stub's —
    `select=["E", "F"]` works, so it must type-check.

    A closed set of values is the one place a narrow type earns itself: a
    `Literal` makes the IDE offer the values, and the tool would reject a
    non-member anyway.
    """
    if option.type_name == "bool":
        return "_Flag"
    if option.type_name == "optvalue":
        return "_ValuedFlag"  # usable bare or with a value — `--gpg-sign[=<key>]`
    if option.choices:
        literal = "Literal[" + ", ".join(repr(c) for c in option.choices) + "]"
        return f"{literal} | Sequence[{literal}] | None"
    return "_Value"


def _docstring(verb: Verb) -> str:
    """The verb's own help, plus one `Args:` entry per flag.

    Google-style because two readers want it: Pylance surfaces a
    parameter's line on hover and in the completion popup, and griffe reads
    the same section to build the reference page — so the tool's help text
    is written once and lands in both.
    """
    documented = [o for o in _unique(verb.options) if o.help or o.negation]
    if not verb.help and not documented:
        return ""
    summary = textwrap.wrap(
        _esc(verb.help) or "Run this verb.",
        width=84,
        initial_indent=" " * 8,
        subsequent_indent=" " * 8,
        break_long_words=False,
        break_on_hyphens=False,
    ) or [" " * 8 + "Run this verb."]
    summary = _md_safe(summary)
    summary[0] = '        """' + summary[0].lstrip()
    lines = list(summary)
    if documented:
        lines.append("")
        lines.append("        Args:")
        for option in documented:
            lines.extend(_arg_lines(option))
    lines.append('        """')
    return "\n".join(lines)


# A wrapped docstring line whose first non-space character opens a Markdown
# block renders as that block in the reference page (griffe reads these).
# Python-Markdown is lenient: `#2` (git's merge-stage notation) is a header
# and `>x` a blockquote, no space required. Both escape as `\#` / `\>`.
_LEADING_MD = re.compile(r"^(#|>)")


def _md_safe(lines: list[str]) -> list[str]:
    """Escape a Markdown block marker a wrap left at a line's start.

    The backslash is doubled: this text becomes a docstring in the
    generated `.pyi`, where a lone `\\#` would be an invalid escape
    sequence — `\\\\#` is the literal `\\#` that Markdown renders as `#`.
    """
    out: list[str] = []
    for line in lines:
        indent = line[: len(line) - len(line.lstrip())]
        content = line[len(indent) :]
        out.append(f"{indent}\\\\{content}" if _LEADING_MD.match(content) else line)
    return out


def _arg_lines(option: Option) -> list[str]:
    """One `Args:` entry, wrapped, with the `off` spelling when it matters."""
    text = _esc(option.help).rstrip(".")
    if option.type_name.startswith("list[") or option.type_name.endswith("[]"):
        text = f"{text}. May be repeated: a list emits the flag once per item"
    if option.type_name == "optvalue":
        text = f"{text}. Value optional: `True` for the bare flag, or pass one"
    if option.negation:
        default_on = option.default is True
        lead = "Defaults on — " if default_on else ""
        text = f"{text}. {lead}`{option.name}=off` emits `{option.negation}`"
    elif option.default not in (None, "", False):
        text = f"{text}. Defaults to `{option.default}`"
    wrapped = textwrap.wrap(
        f"{_safe(option.name)}: {text}.".replace("  ", " "),
        width=84,
        initial_indent=" " * 12,
        subsequent_indent=" " * 16,
        break_long_words=False,
        break_on_hyphens=False,
    )
    return _md_safe(wrapped) or [f"{' ' * 12}{_safe(option.name)}: ."]
