"""Render a `ToolSpec` as the stub a type checker reads.

The bridge in `tools.py` translates keyword arguments mechanically and will
happily pass a flag no stub has heard of — that is what keeps it from going
stale. The stub is the other half: it tells an IDE what the installed tool
*currently* accepts, so the flags complete and their help text is right
there on hover, without importing the tool to find out.

Three things make a generated stub better than a hand-written one:

* it says what the tool says, because it was read from the tool;
* it can be regenerated, so drift is a diff rather than an archaeology
  exercise (`fm footman tools audit` is that diff, run in CI);
* it can carry the tool's own prose per flag, including the one fact a
  bridge can never infer — how *this* tool spells "off".

Every generated verb still ends in `**flags: Any`, so a stub that lags the
installed tool degrades a hint and never a run.
"""

from __future__ import annotations

import textwrap
from collections.abc import Iterable

from footman._toolspec import Option, ToolSpec, Verb

_HEADER = """\
# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from {name} {version} on {platform}. In-process: {in_process}.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
{imports}
"""


def render(
    spec: ToolSpec,
    *,
    platform: str = "",
    class_name: str = "",
    in_process: str = "",
) -> str:
    """The full text of `_stubs/<tool>.pyi` for *spec*."""
    root = class_name or _class_name(spec.name)
    tree = _tree(spec.verbs)
    classes = _classes(tree, root)
    header = _HEADER.format(
        name=spec.name,
        version=spec.version or "an unpinned version",
        platform=platform or "this machine",
        in_process=in_process or ("available" if spec.in_process else "no"),
        imports=_imports("\n".join(classes)),
    )
    return "\n".join([header, *classes])


def _imports(body: str) -> str:
    """Just the imports the body uses — an unused one fails the lint gate."""
    import re

    typing = ["Any"] + (["Literal"] if "Literal[" in body else [])
    names = ["Tool"] + [n for n in ("_Flag", "_Value") if re.search(rf"\b{n}\b", body)]
    lines = []
    if "Sequence[" in body:
        lines.append("from collections.abc import Sequence")
    lines.append(f"from typing import {', '.join(typing)}")
    lines.append("")
    lines.append(f"from footman.tools import {', '.join(names)}")
    return "\n".join(lines)


def _class_name(name: str) -> str:
    """`markdownlint-cli2` → `_MarkdownlintCli2`."""
    return "_" + "".join(part.title() for part in name.replace("-", "_").split("_"))


def _tree(verbs: Iterable[Verb]) -> dict[str, object]:
    """Nest dotted verb names: `compose.up` hangs under `compose`."""
    tree: dict[str, object] = {}
    for verb in verbs:
        node = tree
        parts = verb.name.split(".") if verb.name else []
        for part in parts[:-1]:
            child = node.setdefault(part, {})
            node = child if isinstance(child, dict) else {}
        node[parts[-1] if parts else ""] = verb
    return tree


def _classes(tree: dict[str, object], name: str) -> list[str]:
    """This class, plus one for every subgroup below it, deepest first."""
    out: list[str] = []
    body: list[str] = []
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, dict):
            child = f"{name}{key.title().replace('_', '')}"
            out.extend(_classes(node, child))
            body.append(f"    {key}: {child}")
    for key in sorted(tree):
        node = tree[key]
        if isinstance(node, Verb):
            body.append(_method(node, key))
    out.append(f"class {name}(Tool):\n" + ("\n".join(body) or "    ..."))
    return out


def _method(verb: Verb, key: str) -> str:
    """One verb as a stub method — or `__call__` for a tool's own options."""
    name = key or "__call__"
    override = "  # type: ignore[override]" if name == "__call__" else ""
    lines = [f"    def {name}({override}"] if override else [f"    def {name}("]
    lines.append("        self,")
    lines.append("        *args: str,")
    seen: set[str] = set()
    for option in _unique(verb.options):
        seen.add(option.name)
        lines.append(f"        {_safe(option.name)}: {_annotation(option)} = ...,")
    lines.append("        nofail: bool = False,")
    lines.append("        in_process: bool | None = None,")
    lines.append("        **flags: Any,")
    lines.append("    ) -> int:")
    doc = _docstring(verb)
    if doc:
        lines.append(doc)
    lines.append("        ...")
    return "\n".join(lines)


def _unique(options: tuple[Option, ...]) -> list[Option]:
    """One parameter per keyword — a repeat would be a syntax error."""
    seen: dict[str, Option] = {}
    for option in options:
        seen.setdefault(_safe(option.name), option)
    return list(seen.values())


def _safe(name: str) -> str:
    """A flag whose name is a Python keyword takes footman's trailing `_`."""
    import keyword

    return f"{name}_" if keyword.iskeyword(name) else name


def _annotation(option: Option) -> str:
    """The stub's declared type for one option.

    Deliberately wide, because the stub's contract is to suggest and never
    to forbid. `_Value` takes a sequence as well as a scalar for *every*
    option, since the bridge repeats a flag for each item and whether the
    tool accepts repetition is the tool's business, not the stub's —
    `select=["E", "F"]` works, so it must type-check.

    A closed set of values is the one place a narrow type earns itself: a
    `Literal` makes the IDE offer the values, and the tool would reject a
    non-member anyway.
    """
    if option.type_name == "bool":
        return "_Flag"
    if option.choices:
        literal = "Literal[" + ", ".join(repr(c) for c in option.choices) + "]"
        return f"{literal} | Sequence[{literal}] | None"
    return "_Value"


def _docstring(verb: Verb) -> str:
    """The verb's own help, plus one `Args:` entry per flag.

    Google-style because two readers want it: Pylance surfaces a
    parameter's line on hover and in the completion popup, and griffe reads
    the same section to build the reference page — so the tool's help text
    is written once and lands in both.
    """
    documented = [o for o in _unique(verb.options) if o.help or o.negation]
    if not verb.help and not documented:
        return ""
    summary = textwrap.wrap(
        verb.help or "Run this verb.",
        width=84,
        initial_indent=" " * 8,
        subsequent_indent=" " * 8,
        break_long_words=False,
        break_on_hyphens=False,
    ) or [" " * 8 + "Run this verb."]
    summary[0] = '        """' + summary[0].lstrip()
    lines = list(summary)
    if documented:
        lines.append("")
        lines.append("        Args:")
        for option in documented:
            lines.extend(_arg_lines(option))
    lines.append('        """')
    return "\n".join(lines)


def _arg_lines(option: Option) -> list[str]:
    """One `Args:` entry, wrapped, with the `off` spelling when it matters."""
    text = option.help.rstrip(".")
    if option.type_name.startswith("list[") or option.type_name.endswith("[]"):
        text = f"{text}. May be repeated: a list emits the flag once per item"
    if option.negation:
        default_on = option.default is True
        lead = "Defaults on — " if default_on else ""
        text = f"{text}. {lead}`{option.name}=off` emits `{option.negation}`"
    elif option.default not in (None, "", False):
        text = f"{text}. Defaults to `{option.default}`"
    wrapped = textwrap.wrap(
        f"{_safe(option.name)}: {text}.".replace("  ", " "),
        width=84,
        initial_indent=" " * 12,
        subsequent_indent=" " * 16,
        break_long_words=False,
        break_on_hyphens=False,
    )
    return wrapped or [f"{' ' * 12}{_safe(option.name)}: ."]
