# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from pyproject-build 1.5.0 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result, Tool, _Flag, _Value

class Build(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        config_json: _Value = ...,
        config_setting: _Value = ...,
        dependency_constraints_txt: _Value = ...,
        installer: _Flag = ...,
        metadata: _Flag = ...,
        no_isolation: _Value = ...,
        outdir: _Value = ...,
        quiet: _Flag = ...,
        sdist: _Flag = ...,
        skip_dependency_check: _Flag = ...,
        verbose: _Flag = ...,
        wheel: _Flag = ...,
        **flags: Any,
    ) -> Result:
        """Run this verb.

        Args:
            config_json: settings to pass to the backend as a JSON object.
            config_setting: settings to pass to the backend.
            dependency_constraints_txt: constrain build dependencies using a
                constraints.txt when installing dependencies.
            installer: Python package installer to use (defaults to pip).
            metadata: print out a wheel's metadata in JSON format.
            outdir: output directory (defaults to {srcdir}/dist).
            quiet: reduce verbosity.
            sdist: build a source distribution (disables the default behavior).
            skip_dependency_check: do not check that build dependencies are
                installed.
            verbose: increase verbosity.
            wheel: build a wheel (disables the default behavior).
        """
        ...
