# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from coverage 7.15.2 on macOS. In-process: default.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag, _Value

class Coverage(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Coverage.py, version 7.15.2 with C extension"""
        ...
    def annotate(
        self,
        *args: str,
        data_file: _Value = ...,
        debug: _Value = ...,
        directory: _Value = ...,
        ignore_errors: _Flag = ...,
        include: _Value = ...,
        keep_combined: _Flag = ...,
        omit: _Value = ...,
        rcfile: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Make annotated copies of the given files, marking statements that are
        executed with > and statements that are missed with !.

        Args:
            data_file: Read coverage data for report generation from this file.
            debug: Debug options, separated by commas.
            directory: Write the output files to DIR.
            ignore_errors: Ignore errors while reading source files.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            keep_combined: Keep original coverage files, otherwise they are deleted
                after combining.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            rcfile: Specify configuration file.
        """
        ...
    def combine(
        self,
        *args: str,
        append: _Flag = ...,
        data_file: _Value = ...,
        debug: _Value = ...,
        keep: _Flag = ...,
        quiet: _Flag = ...,
        rcfile: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Combine data from multiple coverage files. The combined results are written
        to a single file representing the union of the data. The positional
        arguments are data files or directories containing

        Args:
            append: Append data to the data file.
            data_file: Base name of the data files to operate on.
            debug: Debug options, separated by commas.
            keep: Keep original coverage files, otherwise they are deleted.
            quiet: Don't print messages about what is happening.
            rcfile: Specify configuration file.
        """
        ...
    def erase(
        self,
        *,
        data_file: _Value = ...,
        debug: _Value = ...,
        rcfile: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Erase previously collected coverage data.

        Args:
            data_file: Base name of the data files to operate on.
            debug: Debug options, separated by commas.
            rcfile: Specify configuration file.
        """
        ...
    def html(
        self,
        *args: str,
        contexts: _Value = ...,
        data_file: _Value = ...,
        debug: _Value = ...,
        directory: _Value = ...,
        fail_under: _Value = ...,
        ignore_errors: _Flag = ...,
        include: _Value = ...,
        keep_combined: _Flag = ...,
        omit: _Value = ...,
        precision: _Value = ...,
        quiet: _Flag = ...,
        rcfile: _Value = ...,
        show_contexts: _Flag = ...,
        skip_covered: _Flag = ...,
        skip_empty: _Flag = ...,
        title: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Create an HTML report of coverage results. Each file gets its own page, with
        the source decorated to show executed, excluded, and missed lines.

        Args:
            contexts: Only display data from lines covered in the given contexts.
                May be repeated: a list emits the flag once per item.
            data_file: Read coverage data for report generation from this file.
            debug: Debug options, separated by commas.
            directory: Write the output files to DIR.
            fail_under: Exit with a status of 2 if the total coverage is less than
                MIN.
            ignore_errors: Ignore errors while reading source files.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            keep_combined: Keep original coverage files, otherwise they are deleted
                after combining.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            precision: Number of digits after the decimal point to display for
                reported coverage percentages.
            quiet: Don't print messages about what is happening.
            rcfile: Specify configuration file.
            show_contexts: Show contexts for covered lines.
            skip_covered: Skip files with 100% coverage. `skip_covered=off` emits
                `--no-skip-covered`.
            skip_empty: Skip files with no code.
            title: A text string to use as the title on the HTML.
        """
        ...
    def json(
        self,
        *args: str,
        contexts: _Value = ...,
        data_file: _Value = ...,
        debug: _Value = ...,
        fail_under: _Value = ...,
        ignore_errors: _Flag = ...,
        include: _Value = ...,
        keep_combined: _Flag = ...,
        omit: _Value = ...,
        pretty_print: _Flag = ...,
        quiet: _Flag = ...,
        rcfile: _Value = ...,
        show_contexts: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Generate a JSON report of coverage results.

        Args:
            contexts: Only display data from lines covered in the given contexts.
                May be repeated: a list emits the flag once per item.
            data_file: Read coverage data for report generation from this file.
            debug: Debug options, separated by commas.
            fail_under: Exit with a status of 2 if the total coverage is less than
                MIN.
            ignore_errors: Ignore errors while reading source files.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            keep_combined: Keep original coverage files, otherwise they are deleted
                after combining.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            pretty_print: Format the JSON for human readers.
            quiet: Don't print messages about what is happening.
            rcfile: Specify configuration file.
            show_contexts: Show contexts for covered lines.
        """
        ...
    def report(
        self,
        *args: str,
        contexts: _Value = ...,
        data_file: _Value = ...,
        debug: _Value = ...,
        fail_under: _Value = ...,
        format: _Value = ...,
        ignore_errors: _Flag = ...,
        include: _Value = ...,
        keep_combined: _Flag = ...,
        omit: _Value = ...,
        precision: _Value = ...,
        rcfile: _Value = ...,
        show_missing: _Flag = ...,
        skip_covered: _Flag = ...,
        skip_empty: _Flag = ...,
        sort: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Report coverage statistics on modules.

        Args:
            contexts: Only display data from lines covered in the given contexts.
                May be repeated: a list emits the flag once per item.
            data_file: Read coverage data for report generation from this file.
            debug: Debug options, separated by commas.
            fail_under: Exit with a status of 2 if the total coverage is less than
                MIN.
            format: Output format, either text (default), markdown, or total.
            ignore_errors: Ignore errors while reading source files.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            keep_combined: Keep original coverage files, otherwise they are deleted
                after combining.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            precision: Number of digits after the decimal point to display for
                reported coverage percentages.
            rcfile: Specify configuration file.
            show_missing: Show line numbers of statements in each module that
                weren't executed.
            skip_covered: Skip files with 100% coverage. `skip_covered=off` emits
                `--no-skip-covered`.
            skip_empty: Skip files with no code.
            sort: Sort the report by the named column: name, stmts, miss, branch,
                brpart, or cover.
        """
        ...
    def run(
        self,
        pyfile: str,
        /,
        *args: str,
        append: _Flag = ...,
        branch: _Flag = ...,
        concurrency: _Value = ...,
        context: _Value = ...,
        data_file: _Value = ...,
        debug: _Value = ...,
        include: _Value = ...,
        module: _Flag = ...,
        omit: _Value = ...,
        parallel_mode: _Flag = ...,
        pylib: _Flag = ...,
        rcfile: _Value = ...,
        save_signal: _Value = ...,
        source: _Value = ...,
        timid: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run a Python program, measuring code execution.

        Args:
            append: Append data to the data file.
            branch: Measure branch coverage in addition to statement coverage.
            concurrency: Properly measure code using a concurrency library.
            context: The context label to record for this coverage run.
            data_file: Write the recorded coverage data to this file.
            debug: Debug options, separated by commas.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            module: <pyfile> is an importable Python module, not a script path, to
                be run as 'python -m' would run it.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            parallel_mode: Append a unique suffix to the data file name to collect
                separate data from multiple processes.
            pylib: Measure coverage even inside the Python installed library, which
                isn't done by default.
            rcfile: Specify configuration file.
            save_signal: Specify a signal that will trigger coverage to write its
                collected data.
            source: A list of directories or importable names of code to measure.
                May be repeated: a list emits the flag once per item.
            timid: Use the slower Python trace function core.
        """
        ...
    def xml(
        self,
        *args: str,
        data_file: _Value = ...,
        debug: _Value = ...,
        fail_under: _Value = ...,
        ignore_errors: _Flag = ...,
        include: _Value = ...,
        keep_combined: _Flag = ...,
        omit: _Value = ...,
        quiet: _Flag = ...,
        rcfile: _Value = ...,
        skip_empty: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Generate an XML report of coverage results.

        Args:
            data_file: Read coverage data for report generation from this file.
            debug: Debug options, separated by commas.
            fail_under: Exit with a status of 2 if the total coverage is less than
                MIN.
            ignore_errors: Ignore errors while reading source files.
            include: Include only files whose paths match one of these patterns. May
                be repeated: a list emits the flag once per item.
            keep_combined: Keep original coverage files, otherwise they are deleted
                after combining.
            omit: Omit files whose paths match one of these patterns. May be
                repeated: a list emits the flag once per item.
            quiet: Don't print messages about what is happening.
            rcfile: Specify configuration file.
            skip_empty: Skip files with no code.
        """
        ...
    def opts(
        self,
        **flags: Any,
    ) -> Coverage:
        """Bind tool-level global options before the subcommand.

        `tools.docker.opts(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
