# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from djlint 1.42.2 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result, Tool, _Flag, _Value

class Djlint(Tool):
    def __call__(  # type: ignore[override]
        self,
        src: str,
        /,
        *args: str,
        blank_line_after_tag: _Value = ...,
        blank_line_before_tag: _Value = ...,
        check: _Flag = ...,
        close_void_tags: _Flag = ...,
        configuration: _Value = ...,
        custom_blocks: _Value = ...,
        custom_html: _Value = ...,
        exclude: _Value = ...,
        extend_exclude: _Value = ...,
        extension: _Value = ...,
        format_attribute_js_json: _Flag = ...,
        format_attribute_js_json_min_props: _Value = ...,
        format_attribute_js_json_pattern: _Value = ...,
        format_attribute_template_tags: _Flag = ...,
        format_css: _Flag = ...,
        format_js: _Flag = ...,
        github_output: _Flag = ...,
        ignore: _Value = ...,
        ignore_blocks: _Value = ...,
        ignore_case: _Flag = ...,
        include: _Value = ...,
        indent: _Value = ...,
        indent_css: _Value = ...,
        indent_js: _Value = ...,
        line_break_after_multiline_tag: _Flag = ...,
        lint: _Flag = ...,
        linter_output_format: _Value = ...,
        max_attribute_length: _Value = ...,
        max_blank_lines: _Value = ...,
        max_line_length: _Value = ...,
        no_function_formatting: _Flag = ...,
        no_line_after_yaml: _Flag = ...,
        no_set_formatting: _Flag = ...,
        per_file_ignores: _Value = ...,
        preserve_blank_lines: _Flag = ...,
        preserve_class_newlines: _Flag = ...,
        preserve_leading_space: _Flag = ...,
        profile: _Value = ...,
        quiet: _Flag = ...,
        reformat: _Flag = ...,
        require_pragma: _Flag = ...,
        rules: _Value = ...,
        single_attribute_per_line: _Flag = ...,
        statistics: _Flag = ...,
        use_gitignore: _Flag = ...,
        warn: _Flag = ...,
        **flags: Any,
    ) -> Result:
        """djLint · HTML template linter and formatter.

        Args:
            blank_line_after_tag: Add an additional blank line after {% <tag> .
            blank_line_before_tag: Add an additional blank line before {% <tag> .
            check: Check formatting on the file(s).
            close_void_tags: Add closing mark on known void tags.
            configuration: Path to global configuration file in djlint.toml,
                .djlint.toml, or .djlintrc format.
            custom_blocks: Indent custom template blocks.
            custom_html: Indent custom HTML tags.
            exclude: Override the default exclude paths.
            extend_exclude: Add additional paths to the default exclude.
            extension: File extension to check. Defaults to `html`.
            format_attribute_js_json: Also format JavaScript/JSON inside HTML
                attributes.
            format_attribute_js_json_min_props: Minimum number of properties to
                treat attribute content as JS/JSON.
            format_attribute_js_json_pattern: Regex pattern to match JavaScript
                attributes.
            format_attribute_template_tags: Attempt to format template syntax inside
                of tag attributes.
            format_css: Also format contents of <style> tags.
            format_js: Also format contents of <script> tags.
            github_output: Output GitHub-compatible formatting.
            ignore: Codes to ignore.
            ignore_blocks: Comma list of template blocks to not indent.
            ignore_case: Do not fix case on known html tags.
            include: Codes to include.
            indent: Indent spacing. Defaults to `4`.
            indent_css: Set CSS indent level.
            indent_js: Set JS indent level.
            line_break_after_multiline_tag: Do not condense the content of
                multi-line tags into the line of the last attribute.
            lint: Lint for common issues.
            linter_output_format: Customize order of linter output message.
            max_attribute_length: Max attribute length. Defaults to `70`.
            max_blank_lines: Consolidate blank lines down to x lines. Defaults to
                `0`.
            max_line_length: Max line length. Defaults to `120`.
            no_function_formatting: Do not attempt to format function contents.
            no_line_after_yaml: Do not add a blank line after yaml front matter.
            no_set_formatting: Do not attempt to format set contents.
            per_file_ignores: Ignore linter rules on a per-file basis. May be
                repeated: a list emits the flag once per item.
            preserve_blank_lines: Attempt to preserve blank lines.
            preserve_class_newlines: Preserve line breaks inside multiline class
                attributes.
            preserve_leading_space: Attempt to preserve leading space on text.
            profile: Enable defaults by template language. Defaults to `html`.
            quiet: Do not print diff when reformatting.
            reformat: Reformat the file(s).
            require_pragma: Only format or lint files that starts with a comment
                with the text 'djlint:on'.
            rules: Path to custom rules file in .djlint_rules.yaml format.
            single_attribute_per_line: When an opening tag wraps, put each attribute
                on its own line.
            statistics: Count the number of occurrences of each error/warning code.
            use_gitignore: Use .gitignore file to extend excludes.
            warn: Return errors as warnings.
        """
        ...
