# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from eclint 0.6.0-wk.5 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result, Tool, _Flag, _Value

class Eclint(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        color: _Value = ...,
        cpuprofile: _Value = ...,
        exclude: _Value = ...,
        fix: _Flag = ...,
        memprofile: _Value = ...,
        no_gitignore: _Flag = ...,
        show_all_errors: _Flag = ...,
        show_error_quantity: _Value = ...,
        summary: _Flag = ...,
        v: _Value = ...,
        vmodule: _Value = ...,
        **flags: Any,
    ) -> Result:
        """Run this verb.

        Args:
            color: use color when printing; can be "always", "auto", or "never".
                Defaults to `auto`.
            cpuprofile: write cpu profile to file.
            exclude: paths to exclude.
            fix: enable fixing instead of error reporting.
            memprofile: write mem profile to file.
            no_gitignore: do not respect .gitignore rules when walking directories.
            show_all_errors: display all errors for each file (otherwise 10 are
                kept).
            show_error_quantity: display only the first n errors (0 means all).
                Defaults to `10`.
            summary: enable the summary view.
            v: number for the log level verbosity of the testing logger.
            vmodule: comma-separated list of pattern=N log level settings for files
                matching the patterns.
        """
        ...
