# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from git 2.50.1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag, _Value

class _Git(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """[--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]"""
        ...
    def add(
        self,
        *args: str,
        all: _Flag = ...,
        dry_run: _Flag = ...,
        edit: _Flag = ...,
        force: _Flag = ...,
        intent_to_add: _Flag = ...,
        interactive: _Flag = ...,
        patch: _Flag = ...,
        update: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """interactive picking

        Args:
            all: add changes from all tracked and untracked files. `all=off` emits
                `--no-all`.
            dry_run: dry run. `dry_run=off` emits `--no-dry-run`.
            edit: edit current diff and apply. `edit=off` emits `--no-edit`.
            force: allow adding otherwise ignored files. `force=off` emits
                `--no-force`.
            intent_to_add: record only the fact that the path will be added later.
                `intent_to_add=off` emits `--no-intent-to-add`.
            interactive: interactive picking. `interactive=off` emits
                `--no-interactive`.
            patch: select hunks interactively. `patch=off` emits `--no-patch`.
            update: update tracked files. `update=off` emits `--no-update`.
            verbose: be verbose. `verbose=off` emits `--no-verbose`.
        """
        ...
    def branch(
        self,
        *args: str,
        all: _Flag = ...,
        contains: _Value = ...,
        copy: _Flag = ...,
        delete: _Flag = ...,
        force: _Flag = ...,
        ignore_case: _Flag = ...,
        list: _Flag = ...,
        merged: _Value = ...,
        move: _Flag = ...,
        no_contains: _Value = ...,
        no_merged: _Value = ...,
        quiet: _Flag = ...,
        remotes: _Flag = ...,
        set_upstream_to: _Value = ...,
        track: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git branch [<options>] [-f] [--recurse-submodules] <branch-name>
        [<start-point>]

        Args:
            all: list both remote-tracking and local branches.
            contains: print only branches that contain the commit.
            copy: copy a branch and its reflog. `copy=off` emits `--no-copy`.
            delete: delete fully merged branch. `delete=off` emits `--no-delete`.
            force: force creation, move/rename, deletion. `force=off` emits
                `--no-force`.
            ignore_case: sorting and filtering are case insensitive.
                `ignore_case=off` emits `--no-ignore-case`.
            list: list branch names. `list=off` emits `--no-list`.
            merged: print only branches that are merged.
            move: move/rename a branch and its reflog. `move=off` emits `--no-move`.
            no_contains: print only branches that don't contain the commit.
            no_merged: print only branches that are not merged.
            quiet: suppress informational messages. `quiet=off` emits `--no-quiet`.
            remotes: act on remote-tracking branches.
            set_upstream_to: change the upstream info. `set_upstream_to=off` emits
                `--no-set-upstream-to`.
            track: set branch tracking configuration. `track=off` emits
                `--no-track`.
            verbose: show hash and subject, give twice for upstream branch.
                `verbose=off` emits `--no-verbose`.
        """
        ...
    def checkout(
        self,
        *args: str,
        detach: _Flag = ...,
        force: _Flag = ...,
        merge: _Flag = ...,
        ours: _Flag = ...,
        patch: _Flag = ...,
        quiet: _Flag = ...,
        theirs: _Flag = ...,
        track: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git checkout [<options>] [<branch>] -- <file>...

        Args:
            detach: detach HEAD at named commit. `detach=off` emits `--no-detach`.
            force: force checkout (throw away local modifications). `force=off`
                emits `--no-force`.
            merge: perform a 3-way merge with the new branch. `merge=off` emits
                `--no-merge`.
            ours: checkout our version for unmerged files.
            patch: select hunks interactively. `patch=off` emits `--no-patch`.
            quiet: suppress progress reporting. `quiet=off` emits `--no-quiet`.
            theirs: checkout their version for unmerged files.
            track: set branch tracking configuration. `track=off` emits
                `--no-track`.
        """
        ...
    def clone(
        self,
        *args: str,
        branch: _Value = ...,
        checkout: _Flag = ...,
        config: _Value = ...,
        hardlinks: _Flag = ...,
        ipv4: _Flag = ...,
        ipv6: _Flag = ...,
        jobs: _Value = ...,
        local: _Flag = ...,
        origin: _Value = ...,
        quiet: _Flag = ...,
        shared: _Flag = ...,
        upload_pack: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """initialize submodules in the clone

        Args:
            branch: checkout <branch> instead of the remote's HEAD. `branch=off`
                emits `--no-branch`.
            checkout: opposite of --no-checkout. `checkout=off` emits
                `--no-checkout`.
            config: set config inside the new repository. `config=off` emits
                `--no-config`.
            hardlinks: opposite of --no-hardlinks. `hardlinks=off` emits
                `--no-hardlinks`.
            ipv4: use IPv4 addresses only.
            ipv6: use IPv6 addresses only.
            jobs: number of submodules cloned in parallel. `jobs=off` emits
                `--no-jobs`.
            local: to clone from a local repository. `local=off` emits `--no-local`.
            origin: use <name> instead of 'origin' to track upstream. `origin=off`
                emits `--no-origin`.
            quiet: be more quiet. `quiet=off` emits `--no-quiet`.
            shared: setup as shared repository. `shared=off` emits `--no-shared`.
            upload_pack: path to git-upload-pack on the remote. `upload_pack=off`
                emits `--no-upload-pack`.
            verbose: be more verbose. `verbose=off` emits `--no-verbose`.
        """
        ...
    def commit(
        self,
        *args: str,
        all: _Flag = ...,
        edit: _Flag = ...,
        file: _Value = ...,
        gpg_sign: _Flag = ...,
        include: _Flag = ...,
        message: _Value = ...,
        null: _Flag = ...,
        only: _Flag = ...,
        patch: _Flag = ...,
        post_rewrite: _Flag = ...,
        quiet: _Flag = ...,
        reedit_message: _Value = ...,
        reuse_message: _Value = ...,
        signoff: _Flag = ...,
        template: _Value = ...,
        trailer: _Value = ...,
        untracked_files: _Flag = ...,
        verbose: _Flag = ...,
        verify: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """[--dry-run] [(-c | -C | --squash) <commit> | --fixup
        [(amend|reword):]<commit>]

        Args:
            all: commit all changed files. `all=off` emits `--no-all`.
            edit: force edit of commit. `edit=off` emits `--no-edit`.
            file: read message from file. `file=off` emits `--no-file`.
            gpg_sign: GPG sign commit. `gpg_sign=off` emits `--no-gpg-sign`.
            include: add specified files to index for commit. `include=off` emits
                `--no-include`.
            message: commit message. `message=off` emits `--no-message`.
            null: terminate entries with NUL. `null=off` emits `--no-null`.
            only: commit only specified files. `only=off` emits `--no-only`.
            patch: interactively add changes. `patch=off` emits `--no-patch`.
            post_rewrite: opposite of --no-post-rewrite. `post_rewrite=off` emits
                `--no-post-rewrite`.
            quiet: suppress summary after successful commit. `quiet=off` emits
                `--no-quiet`.
            reedit_message: reuse and edit message from specified commit.
                `reedit_message=off` emits `--no-reedit-message`.
            reuse_message: reuse message from specified commit. `reuse_message=off`
                emits `--no-reuse-message`.
            signoff: add a Signed-off-by trailer. `signoff=off` emits
                `--no-signoff`.
            template: use specified template file. `template=off` emits
                `--no-template`.
            trailer: add custom trailer(s).
            untracked_files: show untracked files, optional modes: all, normal, no.
                `untracked_files=off` emits `--no-untracked-files`.
            verbose: show diff in commit message template. `verbose=off` emits
                `--no-verbose`.
            verify: opposite of --no-verify. `verify=off` emits `--no-verify`.
        """
        ...
    def describe(
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git describe [--all] [--tags] [--contains] [--abbrev=<n>]
        --dirty[=<mark>]
        """
        ...
    def diff(
        self,
        *args: str,
        abbrev: _Value = ...,
        find_copies_harder: _Flag = ...,
        full_index: _Flag = ...,
        name_only: _Flag = ...,
        name_status: _Flag = ...,
        numstat: _Flag = ...,
        patch_with_raw: _Flag = ...,
        patch_with_stat: _Flag = ...,
        pickaxe_all: _Flag = ...,
        stat: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]

        Args:
            abbrev: abbreviate object names in diff-tree header and diff-raw.
            find_copies_harder: try unchanged files as candidate for copy detection.
            full_index: show full object name on index lines.
            name_only: show only names of changed files.
            numstat: show numeric diffstat instead of patch.
            patch_with_raw: output both a patch and the diff-raw format.
            patch_with_stat: output a patch and prepend its diffstat.
            pickaxe_all: show all files diff when -S is used and hit is found.
            stat: show diffstat instead of patch.
        """
        ...
    def fetch(
        self,
        *args: str,
        append: _Flag = ...,
        force: _Flag = ...,
        ipv4: _Flag = ...,
        ipv6: _Flag = ...,
        jobs: _Value = ...,
        keep: _Flag = ...,
        multiple: _Flag = ...,
        prune: _Flag = ...,
        prune_tags: _Flag = ...,
        quiet: _Flag = ...,
        refetch: _Flag = ...,
        refmap: _Value = ...,
        server_option: _Value = ...,
        tags: _Flag = ...,
        unshallow: _Flag = ...,
        update_head_ok: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git fetch [<options>] <group>

        Args:
            append: append to .git/FETCH_HEAD instead of overwriting. `append=off`
                emits `--no-append`.
            force: force overwrite of local reference. `force=off` emits
                `--no-force`.
            ipv4: use IPv4 addresses only.
            ipv6: use IPv6 addresses only.
            jobs: number of submodules fetched in parallel. `jobs=off` emits
                `--no-jobs`.
            keep: keep downloaded pack. `keep=off` emits `--no-keep`.
            multiple: fetch from multiple remotes. `multiple=off` emits
                `--no-multiple`.
            prune: prune remote-tracking branches no longer on remote. `prune=off`
                emits `--no-prune`.
            prune_tags: . `prune_tags=off` emits `--no-prune-tags`.
            quiet: be more quiet. `quiet=off` emits `--no-quiet`.
            refetch: re-fetch without negotiating common commits.
            refmap: specify fetch refmap.
            server_option: option to transmit. `server_option=off` emits
                `--no-server-option`.
            tags: fetch all tags and associated objects. `tags=off` emits
                `--no-tags`.
            unshallow: convert to a complete repository.
            update_head_ok: allow updating of HEAD ref. `update_head_ok=off` emits
                `--no-update-head-ok`.
            verbose: be more verbose. `verbose=off` emits `--no-verbose`.
        """
        ...
    def init(
        self,
        *args: str,
        initial_branch: _Value = ...,
        quiet: _Flag = ...,
        shared: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """[--separate-git-dir <git-dir>] [--object-format=<format>]

        Args:
            initial_branch: override the name of the initial branch.
                `initial_branch=off` emits `--no-initial-branch`.
            quiet: be quiet. `quiet=off` emits `--no-quiet`.
            shared: specify that the git repository is to be shared amongst several
                users.
        """
        ...
    def log(
        self,
        *args: str,
        clear_decorations: _Flag = ...,
        quiet: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git show [<options>] <object>...

        Args:
            clear_decorations: clear all previously-defined decoration filters.
            quiet: suppress diff output. `quiet=off` emits `--no-quiet`.
        """
        ...
    def pull(
        self,
        *args: str,
        append: _Flag = ...,
        ff_only: _Flag = ...,
        force: _Flag = ...,
        gpg_sign: _Flag = ...,
        ipv4: _Flag = ...,
        ipv6: _Flag = ...,
        jobs: _Flag = ...,
        keep: _Flag = ...,
        prune: _Flag = ...,
        quiet: _Flag = ...,
        rebase: _Flag = ...,
        refmap: _Value = ...,
        server_option: _Value = ...,
        strategy: _Value = ...,
        strategy_option: _Value = ...,
        tags: _Flag = ...,
        unshallow: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """control for recursive fetching of submodules

        Args:
            append: append to .git/FETCH_HEAD instead of overwriting. `append=off`
                emits `--no-append`.
            ff_only: abort if fast-forward is not possible.
            force: force overwrite of local branch. `force=off` emits `--no-force`.
            gpg_sign: GPG sign commit. `gpg_sign=off` emits `--no-gpg-sign`.
            ipv4: use IPv4 addresses only. `ipv4=off` emits `--no-ipv4`.
            ipv6: use IPv6 addresses only. `ipv6=off` emits `--no-ipv6`.
            jobs: . `jobs=off` emits `--no-jobs`.
            keep: keep downloaded pack. `keep=off` emits `--no-keep`.
            prune: prune remote-tracking branches no longer on remote. `prune=off`
                emits `--no-prune`.
            quiet: be more quiet. `quiet=off` emits `--no-quiet`.
            rebase: incorporate changes by rebasing rather than merging.
                `rebase=off` emits `--no-rebase`.
            refmap: specify fetch refmap.
            server_option: option to transmit. `server_option=off` emits
                `--no-server-option`.
            strategy: merge strategy to use. `strategy=off` emits `--no-strategy`.
            strategy_option: option for selected merge strategy.
                `strategy_option=off` emits `--no-strategy-option`.
            tags: fetch all tags and associated objects. `tags=off` emits
                `--no-tags`.
            unshallow: convert to a complete repository.
            verbose: be more verbose. `verbose=off` emits `--no-verbose`.
        """
        ...
    def push(
        self,
        *args: str,
        delete: _Flag = ...,
        dry_run: _Flag = ...,
        force: _Flag = ...,
        ipv4: _Flag = ...,
        ipv6: _Flag = ...,
        push_option: _Value = ...,
        quiet: _Flag = ...,
        set_upstream: _Flag = ...,
        verbose: _Flag = ...,
        verify: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """repository

        Args:
            delete: delete refs. `delete=off` emits `--no-delete`.
            dry_run: dry run. `dry_run=off` emits `--no-dry-run`.
            force: force updates. `force=off` emits `--no-force`.
            ipv4: use IPv4 addresses only.
            ipv6: use IPv6 addresses only.
            push_option: option to transmit. `push_option=off` emits
                `--no-push-option`.
            quiet: be more quiet. `quiet=off` emits `--no-quiet`.
            set_upstream: set upstream for git pull/status. `set_upstream=off` emits
                `--no-set-upstream`.
            verbose: be more verbose. `verbose=off` emits `--no-verbose`.
            verify: opposite of --no-verify. `verify=off` emits `--no-verify`.
        """
        ...
    def restore(
        self,
        *args: str,
        merge: _Flag = ...,
        ours: _Flag = ...,
        patch: _Flag = ...,
        quiet: _Flag = ...,
        source: _Value = ...,
        staged: _Flag = ...,
        theirs: _Flag = ...,
        worktree: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """which tree-ish to checkout from

        Args:
            merge: perform a 3-way merge with the new branch. `merge=off` emits
                `--no-merge`.
            ours: checkout our version for unmerged files.
            patch: select hunks interactively. `patch=off` emits `--no-patch`.
            quiet: suppress progress reporting. `quiet=off` emits `--no-quiet`.
            source: which tree-ish to checkout from. `source=off` emits
                `--no-source`.
            staged: restore the index. `staged=off` emits `--no-staged`.
            theirs: checkout their version for unmerged files.
            worktree: restore the working tree (default). `worktree=off` emits
                `--no-worktree`.
        """
        ...
    def rev_parse(
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git rev-parse --sq-quote [<arg>...]"""
        ...
    def stash(
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """or: git stash show [-u | --include-untracked | --only-untracked]
        [<diff-options>] [<stash>]
        """
        ...
    def status(
        self,
        *args: str,
        branch: _Flag = ...,
        find_renames: _Flag = ...,
        null: _Flag = ...,
        renames: _Flag = ...,
        short: _Flag = ...,
        untracked_files: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """machine-readable output

        Args:
            branch: show branch information. `branch=off` emits `--no-branch`.
            find_renames: detect renames, optionally set similarity index.
            null: terminate entries with NUL. `null=off` emits `--no-null`.
            renames: opposite of --no-renames. `renames=off` emits `--no-renames`.
            short: show status concisely. `short=off` emits `--no-short`.
            untracked_files: show untracked files, optional modes: all, normal, no.
                `untracked_files=off` emits `--no-untracked-files`.
            verbose: be verbose. `verbose=off` emits `--no-verbose`.
        """
        ...
    def switch(
        self,
        *args: str,
        create: _Value = ...,
        detach: _Flag = ...,
        force: _Flag = ...,
        force_create: _Value = ...,
        merge: _Flag = ...,
        quiet: _Flag = ...,
        track: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """create and switch to a new branch

        Args:
            create: create and switch to a new branch. `create=off` emits
                `--no-create`.
            detach: detach HEAD at named commit. `detach=off` emits `--no-detach`.
            force: force checkout (throw away local modifications). `force=off`
                emits `--no-force`.
            force_create: create/reset and switch to a branch. `force_create=off`
                emits `--no-force-create`.
            merge: perform a 3-way merge with the new branch. `merge=off` emits
                `--no-merge`.
            quiet: suppress progress reporting. `quiet=off` emits `--no-quiet`.
            track: set branch tracking configuration. `track=off` emits
                `--no-track`.
        """
        ...
    def tag(
        self,
        *args: str,
        annotate: _Flag = ...,
        contains: _Value = ...,
        delete: _Flag = ...,
        edit: _Flag = ...,
        file: _Value = ...,
        force: _Flag = ...,
        ignore_case: _Flag = ...,
        list: _Flag = ...,
        local_user: _Value = ...,
        merged: _Value = ...,
        message: _Value = ...,
        no_contains: _Value = ...,
        no_merged: _Value = ...,
        sign: _Flag = ...,
        trailer: _Value = ...,
        verify: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """[(--trailer <token>[(=|:)<value>])...]

        Args:
            annotate: annotated tag, needs a message. `annotate=off` emits
                `--no-annotate`.
            contains: print only tags that contain the commit.
            delete: delete tags.
            edit: force edit of tag message. `edit=off` emits `--no-edit`.
            file: read message from file. `file=off` emits `--no-file`.
            force: replace the tag if exists. `force=off` emits `--no-force`.
            ignore_case: sorting and filtering are case insensitive.
                `ignore_case=off` emits `--no-ignore-case`.
            list: list tag names.
            local_user: use another key to sign the tag. `local_user=off` emits
                `--no-local-user`.
            merged: print only tags that are merged.
            message: tag message.
            no_contains: print only tags that don't contain the commit.
            no_merged: print only tags that are not merged.
            sign: annotated and GPG-signed tag. `sign=off` emits `--no-sign`.
            trailer: add custom trailer(s).
            verify: verify tags.
        """
        ...
    def worktree(
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """[--orphan] [(-b | -B) <new-branch>] <path> [<commit-ish>]"""
        ...
