# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from git-cliff 2.13.1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from collections.abc import Sequence
from typing import Any, Literal

from footman.tools import Tool, _Flag, _Value

class GitCliff(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        azure_devops_repo: _Value = ...,
        azure_devops_token: _Value = ...,
        bitbucket_repo: _Value = ...,
        bitbucket_token: _Value = ...,
        body: _Value = ...,
        bump: _Value = ...,
        bumped_version: _Flag = ...,
        config: _Value = ...,
        config_url: _Value = ...,
        context: _Flag = ...,
        count_tags: _Value = ...,
        current: _Flag = ...,
        exclude_path: _Value = ...,
        from_context: _Value = ...,
        gitea_repo: _Value = ...,
        gitea_token: _Value = ...,
        github_repo: _Value = ...,
        github_token: _Value = ...,
        gitlab_repo: _Value = ...,
        gitlab_token: _Value = ...,
        ignore_tags: _Value = ...,
        include_path: _Value = ...,
        init: _Value = ...,
        latest: _Flag = ...,
        no_exec: _Flag = ...,
        offline: _Flag = ...,
        output: _Value = ...,
        prepend: _Value = ...,
        repository: _Value = ...,
        skip_commit: _Value = ...,
        skip_tags: _Value = ...,
        sort: Literal["oldest", "newest"]
        | Sequence[Literal["oldest", "newest"]]
        | None = ...,
        strip: Literal["header", "footer", "all"]
        | Sequence[Literal["header", "footer", "all"]]
        | None = ...,
        tag: _Value = ...,
        tag_pattern: _Value = ...,
        topo_order: _Flag = ...,
        unreleased: _Flag = ...,
        use_branch_tags: _Flag = ...,
        use_native_tls: _Flag = ...,
        verbose: _Flag = ...,
        with_commit: _Value = ...,
        with_tag_message: _Value = ...,
        workdir: _Value = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """git-cliff 2.13.1

        Args:
            azure_devops_repo: Sets the Azure DevOps repository.
            azure_devops_token: Sets the Azure DevOps API token.
            bitbucket_repo: Sets the Bitbucket repository.
            bitbucket_token: Sets the Bitbucket API token.
            body: Sets the template for the changelog body.
            bump: Bumps the version for unreleased changes.
            bumped_version: Prints bumped version for unreleased changes.
            config: Sets the configuration file. Defaults to `cliff.toml`.
            config_url: Sets the URL for the configuration file.
            context: Prints changelog context as JSON.
            count_tags: Sets the tags to count in the changelog.
            current: Processes the commits that belong to the current tag.
            exclude_path: Sets the path to exclude related commits. May be repeated:
                a list emits the flag once per item.
            from_context: Generates changelog from a JSON context.
            gitea_repo: Sets the Gitea repository.
            gitea_token: Sets the Gitea API token.
            github_repo: Sets the GitHub repository.
            github_token: Sets the GitHub API token.
            gitlab_repo: Sets the GitLab repository.
            gitlab_token: Sets the GitLab API token.
            ignore_tags: Sets the tags to ignore in the changelog.
            include_path: Sets the path to include related commits. May be repeated:
                a list emits the flag once per item.
            init: Writes the default configuration file to cliff.toml.
            latest: Processes the commits starting from the latest tag.
            no_exec: Disables the external command execution.
            offline: Disable network access for remote repositories.
            output: Writes output to the given file.
            prepend: Prepends entries to the given changelog file.
            repository: Sets the git repository. May be repeated: a list emits the
                flag once per item.
            skip_commit: Sets commits that will be skipped in the changelog. May be
                repeated: a list emits the flag once per item.
            skip_tags: Sets the tags to skip in the changelog.
            sort: Sets sorting of the commits inside sections. Defaults to `oldest`.
            strip: Strips the given parts from the changelog.
            tag: Sets the tag for the latest version.
            tag_pattern: Sets the regex for matching git tags.
            topo_order: Sorts the tags topologically.
            unreleased: Processes the commits that do not belong to a tag.
            use_branch_tags: Include only the tags that belong to the current
                branch.
            use_native_tls: Load TLS certificates from the native certificate store.
            verbose: Increases the logging verbosity.
            with_commit: Sets custom commit messages to include in the changelog.
                May be repeated: a list emits the flag once per item.
            with_tag_message: Sets custom message for the latest release.
            workdir: Sets the working directory.
        """
        ...
