# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from markdownlint-cli2 0.23.2 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result as _Result
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

class Markdownlint(_Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        config: _Value = ...,
        configPointer: _Value = ...,
        fix: _Flag = ...,
        format: _Flag = ...,
        no_globs: _Flag = ...,
        **flags: Any,
    ) -> _Result:
        """markdownlint-cli2 v0.23.2 (markdownlint v0.41.1)

        Args:
            config: specifies the path to a configuration file to define the base
                configuration.
            configPointer: specifies a JSON Pointer to a configuration object within
                the --config file. Added in 0.22.0.
            fix: updates files to resolve fixable issues (can be overridden in
                configuration).
            format: reads standard input (stdin), applies fixes, writes standard
                output (stdout). Added in 0.19.0.
            no_globs: ignores the "globs" property if present in the top-level
                options object.
        """
        ...
