# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from markdownlint-cli2 0.23.1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag, _Value

class Markdownlint(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        config: _Flag = ...,
        configPointer: _Value = ...,
        fix: _Flag = ...,
        format: _Flag = ...,
        no_globs: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """markdownlint-cli2 v0.23.1 (markdownlint v0.41.1)

        Args:
            config: specifies the path to a configuration file to define the base
                configuration.
            fix: updates files to resolve fixable issues (can be overridden in
                configuration).
            format: reads standard input (stdin), applies fixes, writes standard
                output (stdout).
            no_globs: ignores the "globs" property if present in the top-level
                options object.
        """
        ...
