# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from ninja 1.13.0.git.kitware.jobserver-pipe-1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag

class Ninja(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        quiet: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """if targets are unspecified, builds the 'default' target (see manual).

        Args:
            quiet: don't show progress status, just command output.
            verbose: show all command lines while building.
        """
        ...
