# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from prek 0.4.10 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from collections.abc import Sequence
from typing import Any, Literal

from footman.tools import Tool, _Flag, _Value

class Prek(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        all_files: _Flag = ...,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        directory: _Value = ...,
        dry_run: _Flag = ...,
        fail_fast: _Flag = ...,
        files: _Value = ...,
        from_ref: _Value = ...,
        group: _Value = ...,
        last_commit: _Flag = ...,
        log_file: _Value = ...,
        no_group: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        show_diff_on_failure: _Flag = ...,
        skip: _Value = ...,
        stage: Literal[
            "manual",
            "commit-msg",
            "post-checkout",
            "post-commit",
            "post-merge",
            "post-rewrite",
            "pre-commit",
            "pre-merge-commit",
            "pre-push",
            "pre-rebase",
            "prepare-commit-msg",
        ]
        | Sequence[
            Literal[
                "manual",
                "commit-msg",
                "post-checkout",
                "post-commit",
                "post-merge",
                "post-rewrite",
                "pre-commit",
                "pre-merge-commit",
                "pre-push",
                "pre-rebase",
                "prepare-commit-msg",
            ]
        ]
        | None = ...,
        to_ref: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """A fast Git hook manager written in Rust, designed as a drop-in alternative
        to pre-commit, reimagined.

        Args:
            all_files: Run on all files in the repo.
            cd: Change to directory before running.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            directory: Run hooks on all files in the specified directories.
            dry_run: Do not run the hooks, but print the hooks that would have been
                run.
            fail_fast: Stop running hooks after the first failure.
            files: Specific filenames to run hooks on. May be repeated: a list emits
                the flag once per item.
            from_ref: The original ref in a `<from_ref>...<to_ref>` diff expression.
            group: Run hooks belonging to the specified group.
            last_commit: Run hooks against the last commit.
            log_file: Write trace logs to the specified file.
            no_group: Do not run hooks belonging to the specified group.
            no_progress: Hide all progress outputs.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            show_diff_on_failure: When hooks fail, run `git diff` directly
                afterward.
            skip: Skip the specified hooks or projects.
            stage: The stage during which the hook is fired.
            to_ref: The destination ref in a `from_ref...to_ref` diff expression.
            verbose: Use verbose output.
        """
        ...
    def autoupdate(
        self,
        *,
        bleeding_edge: _Flag = ...,
        cd: _Value = ...,
        check: _Flag = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        cooldown_days: _Value = ...,
        dry_run: _Flag = ...,
        exclude_repo: _Value = ...,
        exclude_tag: _Value = ...,
        exit_code: _Flag = ...,
        freeze: _Flag = ...,
        include_tag: _Value = ...,
        jobs: _Value = ...,
        log_file: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        repo: _Value = ...,
        repo_exclude_tag: _Value = ...,
        repo_include_tag: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Update the `rev` field of repositories in the config file to the latest
        version

        Args:
            bleeding_edge: Update to the bleeding edge of the default branch instead
                of the latest tagged version.
            cd: Change to directory before running.
            check: Alias of `--dry-run --exit-code`.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            cooldown_days: Minimum release age (in days) required for a version to
                be eligible.
            dry_run: Do not write changes to the config file, only display what
                would be changed.
            exclude_repo: Do not update this repository. May be repeated: a list
                emits the flag once per item.
            exclude_tag: Ignore tags matching this glob pattern. May be repeated: a
                list emits the flag once per item.
            exit_code: Exit with status 1 if updates are available.
            freeze: Store "frozen" hashes in `rev` instead of tag names.
            include_tag: Only consider tags matching this glob pattern. May be
                repeated: a list emits the flag once per item.
            jobs: Number of threads to use. Defaults to `0`.
            log_file: Write trace logs to the specified file.
            no_progress: Hide all progress outputs.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            repo: Only update this repository. May be repeated: a list emits the
                flag once per item.
            repo_exclude_tag: Ignore tags matching this glob pattern for a
                repository (`<repo>=<pattern>`). May be repeated: a list emits the
                flag once per item.
            repo_include_tag: Only consider tags matching this glob pattern for a
                repository (`<repo>=<pattern>`). May be repeated: a list emits the
                flag once per item.
            verbose: Use verbose output.
        """
        ...
    def clean(
        self,
        *,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        log_file: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Remove all prek cached data

        Args:
            cd: Change to directory before running.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            log_file: Write trace logs to the specified file.
            no_progress: Hide all progress outputs.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            verbose: Use verbose output.
        """
        ...
    def install(
        self,
        *args: str,
        allow_missing_config: _Flag = ...,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        git_dir: _Value = ...,
        hook_type: Literal[
            "commit-msg",
            "post-checkout",
            "post-commit",
            "post-merge",
            "post-rewrite",
            "pre-commit",
            "pre-merge-commit",
            "pre-push",
            "pre-rebase",
            "prepare-commit-msg",
        ]
        | Sequence[
            Literal[
                "commit-msg",
                "post-checkout",
                "post-commit",
                "post-merge",
                "post-rewrite",
                "pre-commit",
                "pre-merge-commit",
                "pre-push",
                "pre-rebase",
                "prepare-commit-msg",
            ]
        ]
        | None = ...,
        log_file: _Value = ...,
        no_progress: _Flag = ...,
        overwrite: _Flag = ...,
        prepare_hooks: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        skip: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Install prek Git shims into Git's effective hooks directory

        Args:
            allow_missing_config: Allow a missing configuration file.
            cd: Change to directory before running.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            git_dir: Install Git shims into the `hooks` subdirectory of the given
                git directory (`<GIT_DIR>/hooks/`).
            hook_type: Which Git shim(s) to install.
            log_file: Write trace logs to the specified file.
            no_progress: Hide all progress outputs.
            overwrite: Overwrite existing Git shims.
            prepare_hooks: Also prepare environments for all hooks used in the
                config file.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            skip: Skip the specified hooks or projects.
            verbose: Use verbose output.
        """
        ...
    def run(
        self,
        *args: str,
        all_files: _Flag = ...,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        directory: _Value = ...,
        dry_run: _Flag = ...,
        fail_fast: _Flag = ...,
        files: _Value = ...,
        from_ref: _Value = ...,
        group: _Value = ...,
        last_commit: _Flag = ...,
        log_file: _Value = ...,
        no_group: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        show_diff_on_failure: _Flag = ...,
        skip: _Value = ...,
        stage: Literal[
            "manual",
            "commit-msg",
            "post-checkout",
            "post-commit",
            "post-merge",
            "post-rewrite",
            "pre-commit",
            "pre-merge-commit",
            "pre-push",
            "pre-rebase",
            "prepare-commit-msg",
        ]
        | Sequence[
            Literal[
                "manual",
                "commit-msg",
                "post-checkout",
                "post-commit",
                "post-merge",
                "post-rewrite",
                "pre-commit",
                "pre-merge-commit",
                "pre-push",
                "pre-rebase",
                "prepare-commit-msg",
            ]
        ]
        | None = ...,
        to_ref: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run hooks

        Args:
            all_files: Run on all files in the repo.
            cd: Change to directory before running.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            directory: Run hooks on all files in the specified directories.
            dry_run: Do not run the hooks, but print the hooks that would have been
                run.
            fail_fast: Stop running hooks after the first failure.
            files: Specific filenames to run hooks on. May be repeated: a list emits
                the flag once per item.
            from_ref: The original ref in a `<from_ref>...<to_ref>` diff expression.
            group: Run hooks belonging to the specified group.
            last_commit: Run hooks against the last commit.
            log_file: Write trace logs to the specified file.
            no_group: Do not run hooks belonging to the specified group.
            no_progress: Hide all progress outputs.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            show_diff_on_failure: When hooks fail, run `git diff` directly
                afterward.
            skip: Skip the specified hooks or projects.
            stage: The stage during which the hook is fired.
            to_ref: The destination ref in a `from_ref...to_ref` diff expression.
            verbose: Use verbose output.
        """
        ...
    def uninstall(
        self,
        *,
        all: _Flag = ...,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        git_dir: _Value = ...,
        hook_type: Literal[
            "commit-msg",
            "post-checkout",
            "post-commit",
            "post-merge",
            "post-rewrite",
            "pre-commit",
            "pre-merge-commit",
            "pre-push",
            "pre-rebase",
            "prepare-commit-msg",
        ]
        | Sequence[
            Literal[
                "commit-msg",
                "post-checkout",
                "post-commit",
                "post-merge",
                "post-rewrite",
                "pre-commit",
                "pre-merge-commit",
                "pre-push",
                "pre-rebase",
                "prepare-commit-msg",
            ]
        ]
        | None = ...,
        log_file: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Uninstall prek Git shims

        Args:
            all: Uninstall all prek-managed Git shims.
            cd: Change to directory before running.
            color: Whether to use color in output. Defaults to `auto`.
            config: Path to alternate config file.
            git_dir: Uninstall Git shims from the `hooks` subdirectory of the given
                git directory (`<GIT_DIR>/hooks/`).
            hook_type: Which Git shim(s) to uninstall.
            log_file: Write trace logs to the specified file.
            no_progress: Hide all progress outputs.
            quiet: Use quiet output.
            refresh: Refresh all cached data.
            verbose: Use verbose output.
        """
        ...
    def opts(
        self,
        *,
        all_files: _Flag = ...,
        cd: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        directory: _Value = ...,
        dry_run: _Flag = ...,
        fail_fast: _Flag = ...,
        files: _Value = ...,
        from_ref: _Value = ...,
        group: _Value = ...,
        last_commit: _Flag = ...,
        log_file: _Value = ...,
        no_group: _Value = ...,
        no_progress: _Flag = ...,
        quiet: _Flag = ...,
        refresh: _Flag = ...,
        show_diff_on_failure: _Flag = ...,
        skip: _Value = ...,
        stage: Literal[
            "manual",
            "commit-msg",
            "post-checkout",
            "post-commit",
            "post-merge",
            "post-rewrite",
            "pre-commit",
            "pre-merge-commit",
            "pre-push",
            "pre-rebase",
            "prepare-commit-msg",
        ]
        | Sequence[
            Literal[
                "manual",
                "commit-msg",
                "post-checkout",
                "post-commit",
                "post-merge",
                "post-rewrite",
                "pre-commit",
                "pre-merge-commit",
                "pre-push",
                "pre-rebase",
                "prepare-commit-msg",
            ]
        ]
        | None = ...,
        to_ref: _Value = ...,
        verbose: _Flag = ...,
        **flags: Any,
    ) -> Prek:
        """Bind tool-level global options before the subcommand.

        `tools.docker.opts(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
