# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from python 3.13.1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag, _Value

class Python(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        B: _Flag = ...,
        E: _Flag = ...,
        I: _Flag = ...,
        O: _Flag = ...,
        OO: _Flag = ...,
        P: _Flag = ...,
        S: _Flag = ...,
        V: _Flag = ...,
        W: _Value = ...,
        b: _Flag = ...,
        c: _Value = ...,
        check_hash_based_pycs: _Value = ...,
        d: _Flag = ...,
        h: _Flag = ...,
        help_all: _Flag = ...,
        help_env: _Flag = ...,
        help_xoptions: _Value = ...,
        i: _Flag = ...,
        m: _Value = ...,
        q: _Flag = ...,
        s: _Flag = ...,
        specific: _Value = ...,
        u: _Flag = ...,
        v: _Flag = ...,
        x: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run this verb.

        Args:
            B: : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x.
            E: : ignore PYTHON* environment variables (such as PYTHONPATH).
            I: : isolate Python from the user's environment (implies -E and -s).
            O: : remove assert and __debug__-dependent statements; add .opt-1 before
                .pyc extension; also PYTHONOPTIMIZE=x.
            OO: : do -O changes and also discard docstrings; add .opt-2 before .pyc
                extension.
            P: : don't prepend a potentially unsafe path to sys.path; also
                PYTHONSAFEPATH.
            S: : don't imply 'import site' on initialization.
            V: : print the Python version number and exit (also --version) when
                given twice, print more information about the build.
            W: also PYTHONWARNINGS=arg.
            b: : issue warnings about converting bytes/bytearray to str and
                comparing bytes/bytearray with str or bytes with int.
            check_hash_based_pycs: control how Python invalidates hash-based .pyc
                files.
            d: : turn on parser debugging output (for experts only, only works on
                debug builds); also PYTHONDEBUG=x.
            h: : print this help message and exit (also -? or --help).
            i: : inspect interactively after running script; forces a prompt even if
                stdin does not appear to be a terminal; also PYTHONINSPECT=x.
            q: : don't print version and copyright messages on interactive startup.
            s: : don't add user site directory to sys.path; also PYTHONNOUSERSITE=x.
            u: : force the stdout and stderr streams to be unbuffered; this option
                has no effect on stdin; also PYTHONUNBUFFERED=x.
            v: : verbose (trace import statements); also PYTHONVERBOSE=x can be
                supplied multiple times to increase verbosity.
            x: : skip first line of source, allowing use of non-Unix forms of #!cmd.
        """
        ...
