# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from ruff 0.15.21 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from collections.abc import Sequence
from typing import Any, Literal

from footman.tools import Tool, _Flag, _Value

class _RuffFormat(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        cache_dir: _Value = ...,
        check: _Flag = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        diff: _Flag = ...,
        exclude: _Value = ...,
        exit_non_zero_on_format: _Flag = ...,
        extend_exclude: _Value = ...,
        extension: _Value = ...,
        force_exclude: _Flag = ...,
        isolated: _Flag = ...,
        line_length: _Value = ...,
        no_cache: _Flag = ...,
        output_format: Literal[
            "concise",
            "full",
            "json",
            "json-lines",
            "junit",
            "grouped",
            "github",
            "gitlab",
            "pylint",
            "rdjson",
            "azure",
            "sarif",
        ]
        | Sequence[
            Literal[
                "concise",
                "full",
                "json",
                "json-lines",
                "junit",
                "grouped",
                "github",
                "gitlab",
                "pylint",
                "rdjson",
                "azure",
                "sarif",
            ]
        ]
        | None = ...,
        preview: _Flag = ...,
        quiet: _Flag = ...,
        range: _Value = ...,
        respect_gitignore: _Flag = ...,
        silent: _Flag = ...,
        stdin_filename: _Value = ...,
        target_version: Literal[
            "py37", "py38", "py39", "py310", "py311", "py312", "py313", "py314", "py315"
        ]
        | Sequence[
            Literal[
                "py37",
                "py38",
                "py39",
                "py310",
                "py311",
                "py312",
                "py313",
                "py314",
                "py315",
            ]
        ]
        | None = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run the Ruff formatter on the given files or directories

        Args:
            cache_dir: Path to the cache directory.
            check: Avoid writing any formatted files back; instead, exit with a
                non-zero status code if any files would have been modified, and zero
                otherwise.
            color: Control when colored output is used.
            config: Either a path to a TOML configuration file (`pyproject.toml` or
                `ruff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might
                find in a `ruff.toml` configuration file) overriding a specific
                configuration option (e.g., `--config "lint.line-length = 100"` or
                `--config "format.quote-style = 'single'"`). Overrides of individual
                settings using this option always take precedence over all
                configuration files, including configuration files that were also
                specified using `--config`.
            diff: Avoid writing any formatted files back; instead, exit with a
                non-zero status code and the difference between the current file and
                how the formatted file would look like.
            exclude: List of paths, used to omit files and/or directories from
                analysis.
            exit_non_zero_on_format: Exit with a non-zero status code if any files
                were modified via format, even if all files were formatted
                successfully.
            extend_exclude: Like --exclude, but adds additional files and
                directories on top of those already excluded.
            extension: List of mappings from file extension to language (one of
                `python`, `ipynb`, `pyi`). For example, to treat `.ipy` files as
                IPython notebooks, use `--extension ipy:ipynb`.
            force_exclude: Enforce exclusions, even for paths passed to Ruff
                directly on the command-line. Use `--no-force-exclude` to disable.
                `force_exclude=off` emits `--no-force-exclude`.
            isolated: Ignore all configuration files.
            line_length: Set the line-length.
            no_cache: Disable cache reads.
            output_format: Output serialization format for violations, when used
                with `--check`. The default serialization format is "full". Note
                that this option is currently only respected in preview mode. A
                warning will be emitted if this flag is used on stable.
            preview: Enable preview mode; enables unstable formatting. Use
                `--no-preview` to disable. `preview=off` emits `--no-preview`.
            quiet: Print diagnostics, but nothing else.
            range: When specified, Ruff will try to only format the code in the
                given range. It might be necessary to extend the start backwards or
                the end forwards, to fully enclose a logical line. The `<RANGE>`
                uses the format
                `<start_line>:<start_column>-<end_line>:<end_column>`. - The line
                and column numbers are 1 based. - The column specifies the
                nth-unicode codepoint on that line. - The end offset is exclusive. -
                The column numbers are optional. You can write `--range=1-2` instead
                of `--range=1:1-2:1`. - The end position is optional. You can write
                `--range=2` to format the entire document starting from the second
                line. - The start position is optional. You can write `--range=-3`
                to format the first three lines of the document. The option can only
                be used when formatting a single file. Range formatting of notebooks
                is unsupported.
            respect_gitignore: Respect file exclusions via `.gitignore` and other
                standard ignore files. Use `--no-respect-gitignore` to disable.
                `respect_gitignore=off` emits `--no-respect-gitignore`.
            silent: Disable all logging (but still exit with status code "1" upon
                detecting diagnostics).
            stdin_filename: The name of the file when passing it through stdin.
            target_version: The minimum Python version that should be supported.
            verbose: Enable verbose logging.
        """
        ...
