# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from ruff 0.15.21 on macOS. Every verb ends in
# `**flags: Any`: the stub suggests what this tool accepts, and can never
# forbid what the bridge would happily pass.
from collections.abc import Sequence
from typing import Any, Literal

from footman.tools import Tool, _Flag, _Value

class _Ruff(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        isolated: _Flag = ...,
        quiet: _Flag = ...,
        silent: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Ruff: An extremely fast Python linter and code formatter.

        Args:
            color: Control when colored output is used.
            config: Either a path to a TOML configuration file (`pyproject.toml` or
                `ruff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might
                find in a `ruff.toml` configuration file) overriding a specific
                configuration option (e.g., `--config "lint.line-length = 100"` or
                `--config "format.quote-style = 'single'"`). Overrides of individual
                settings using this option always take precedence over all
                configuration files, including configuration files that were also
                specified using `--config`.
            isolated: Ignore all configuration files.
            quiet: Print diagnostics, but nothing else.
            silent: Disable all logging (but still exit with status code "1" upon
                detecting diagnostics).
            verbose: Enable verbose logging.
        """
        ...
    def check(
        self,
        *args: str,
        add_ignore: _Flag = ...,
        add_noqa: _Flag = ...,
        cache_dir: _Value = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        diff: _Flag = ...,
        exclude: _Value = ...,
        exit_non_zero_on_fix: _Flag = ...,
        exit_zero: _Flag = ...,
        extend_exclude: _Value = ...,
        extend_fixable: _Value = ...,
        extend_per_file_ignores: _Value = ...,
        extend_select: _Value = ...,
        extension: _Value = ...,
        fix: _Flag = ...,
        fix_only: _Flag = ...,
        fixable: _Value = ...,
        force_exclude: _Flag = ...,
        ignore: _Value = ...,
        ignore_noqa: _Flag = ...,
        isolated: _Flag = ...,
        no_cache: _Flag = ...,
        output_file: _Value = ...,
        output_format: Literal[
            "concise",
            "full",
            "json",
            "json-lines",
            "junit",
            "grouped",
            "github",
            "gitlab",
            "pylint",
            "rdjson",
            "azure",
            "sarif",
        ]
        | Sequence[
            Literal[
                "concise",
                "full",
                "json",
                "json-lines",
                "junit",
                "grouped",
                "github",
                "gitlab",
                "pylint",
                "rdjson",
                "azure",
                "sarif",
            ]
        ]
        | None = ...,
        per_file_ignores: _Value = ...,
        preview: _Flag = ...,
        quiet: _Flag = ...,
        respect_gitignore: _Flag = ...,
        select: _Value = ...,
        show_files: _Flag = ...,
        show_fixes: _Flag = ...,
        show_settings: _Flag = ...,
        silent: _Flag = ...,
        statistics: _Flag = ...,
        stdin_filename: _Value = ...,
        target_version: Literal[
            "py37", "py38", "py39", "py310", "py311", "py312", "py313", "py314", "py315"
        ]
        | Sequence[
            Literal[
                "py37",
                "py38",
                "py39",
                "py310",
                "py311",
                "py312",
                "py313",
                "py314",
                "py315",
            ]
        ]
        | None = ...,
        unfixable: _Value = ...,
        unsafe_fixes: _Flag = ...,
        verbose: _Flag = ...,
        watch: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run Ruff on the given files or directories

        Args:
            add_ignore: Enable automatic additions of `ruff:ignore` comments to
                failing lines. Optionally provide a reason to append after the rule
                names. Requires preview mode.
            add_noqa: Enable automatic additions of `noqa` directives to failing
                lines. Optionally provide a reason to append after the codes.
            cache_dir: Path to the cache directory.
            color: Control when colored output is used.
            config: Either a path to a TOML configuration file (`pyproject.toml` or
                `ruff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might
                find in a `ruff.toml` configuration file) overriding a specific
                configuration option (e.g., `--config "lint.line-length = 100"` or
                `--config "format.quote-style = 'single'"`). Overrides of individual
                settings using this option always take precedence over all
                configuration files, including configuration files that were also
                specified using `--config`.
            diff: Avoid writing any fixed files back; instead, output a diff for
                each changed file to stdout, and exit 0 if there are no diffs.
                Implies `--fix-only`.
            exclude: List of paths, used to omit files and/or directories from
                analysis.
            exit_non_zero_on_fix: Exit with a non-zero status code if any files were
                modified via fix, even if no lint violations remain.
            exit_zero: Exit with status code "0", even upon detecting lint
                violations.
            extend_exclude: Like --exclude, but adds additional files and
                directories on top of those already excluded.
            extend_fixable: Like --fixable, but adds additional rule codes on top of
                those already specified.
            extend_per_file_ignores: Like `--per-file-ignores`, but adds additional
                ignores on top of those already specified.
            extend_select: Like --select, but adds additional rule codes on top of
                those already specified.
            extension: List of mappings from file extension to language (one of
                `python`, `ipynb`, `pyi`). For example, to treat `.ipy` files as
                IPython notebooks, use `--extension ipy:ipynb`.
            fix: Apply fixes to resolve lint violations. Use `--no-fix` to disable
                or `--unsafe-fixes` to include unsafe fixes. `fix=off` emits
                `--no-fix`.
            fix_only: Apply fixes to resolve lint violations, but don't report on,
                or exit non-zero for, leftover violations. Implies `--fix`. Use
                `--no-fix-only` to disable or `--unsafe-fixes` to include unsafe
                fixes. `fix_only=off` emits `--no-fix-only`.
            fixable: List of rule codes to treat as eligible for fix. Only
                applicable when fix itself is enabled (e.g., via `--fix`).
            force_exclude: Enforce exclusions, even for paths passed to Ruff
                directly on the command-line. Use `--no-force-exclude` to disable.
                `force_exclude=off` emits `--no-force-exclude`.
            ignore: Comma-separated list of rule codes to disable.
            ignore_noqa: Ignore any `# noqa` comments.
            isolated: Ignore all configuration files.
            no_cache: Disable cache reads.
            output_file: Specify file to write the linter output to. Defaults to
                `stdout`.
            output_format: Output serialization format for violations. The default
                serialization format is "full".
            per_file_ignores: List of mappings from file pattern to code to exclude.
            preview: Enable preview mode; checks will include unstable rules and
                fixes. Use `--no-preview` to disable. `preview=off` emits
                `--no-preview`.
            quiet: Print diagnostics, but nothing else.
            respect_gitignore: Respect file exclusions via `.gitignore` and other
                standard ignore files. Use `--no-respect-gitignore` to disable.
                `respect_gitignore=off` emits `--no-respect-gitignore`.
            select: Comma-separated list of rule codes to enable (or ALL, to enable
                all rules).
            show_files: See the files Ruff will be run against with the current
                settings.
            show_fixes: Show an enumeration of all fixed lint violations. Use
                `--no-show-fixes` to disable. `show_fixes=off` emits
                `--no-show-fixes`.
            show_settings: See the settings Ruff will use to lint a given Python
                file.
            silent: Disable all logging (but still exit with status code "1" upon
                detecting diagnostics).
            statistics: Show counts for every rule with at least one violation.
            stdin_filename: The name of the file when passing it through stdin.
            target_version: The minimum Python version that should be supported.
            unfixable: List of rule codes to treat as ineligible for fix. Only
                applicable when fix itself is enabled (e.g., via `--fix`).
            unsafe_fixes: Include fixes that may not retain the original intent of
                the code. Use `--no-unsafe-fixes` to disable. `unsafe_fixes=off`
                emits `--no-unsafe-fixes`.
            verbose: Enable verbose logging.
            watch: Run in watch mode by re-running whenever files change.
        """
        ...
    def clean(
        self,
        *args: str,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        isolated: _Flag = ...,
        quiet: _Flag = ...,
        silent: _Flag = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Clear any caches in the current directory and any subdirectories

        Args:
            color: Control when colored output is used.
            config: Either a path to a TOML configuration file (`pyproject.toml` or
                `ruff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might
                find in a `ruff.toml` configuration file) overriding a specific
                configuration option (e.g., `--config "lint.line-length = 100"` or
                `--config "format.quote-style = 'single'"`). Overrides of individual
                settings using this option always take precedence over all
                configuration files, including configuration files that were also
                specified using `--config`.
            isolated: Ignore all configuration files.
            quiet: Print diagnostics, but nothing else.
            silent: Disable all logging (but still exit with status code "1" upon
                detecting diagnostics).
            verbose: Enable verbose logging.
        """
        ...
    def format(
        self,
        *args: str,
        cache_dir: _Value = ...,
        check: _Flag = ...,
        color: Literal["auto", "always", "never"]
        | Sequence[Literal["auto", "always", "never"]]
        | None = ...,
        config: _Value = ...,
        diff: _Flag = ...,
        exclude: _Value = ...,
        exit_non_zero_on_format: _Flag = ...,
        extend_exclude: _Value = ...,
        extension: _Value = ...,
        force_exclude: _Flag = ...,
        isolated: _Flag = ...,
        line_length: _Value = ...,
        no_cache: _Flag = ...,
        output_format: Literal[
            "concise",
            "full",
            "json",
            "json-lines",
            "junit",
            "grouped",
            "github",
            "gitlab",
            "pylint",
            "rdjson",
            "azure",
            "sarif",
        ]
        | Sequence[
            Literal[
                "concise",
                "full",
                "json",
                "json-lines",
                "junit",
                "grouped",
                "github",
                "gitlab",
                "pylint",
                "rdjson",
                "azure",
                "sarif",
            ]
        ]
        | None = ...,
        preview: _Flag = ...,
        quiet: _Flag = ...,
        range: _Value = ...,
        respect_gitignore: _Flag = ...,
        silent: _Flag = ...,
        stdin_filename: _Value = ...,
        target_version: Literal[
            "py37", "py38", "py39", "py310", "py311", "py312", "py313", "py314", "py315"
        ]
        | Sequence[
            Literal[
                "py37",
                "py38",
                "py39",
                "py310",
                "py311",
                "py312",
                "py313",
                "py314",
                "py315",
            ]
        ]
        | None = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Run the Ruff formatter on the given files or directories

        Args:
            cache_dir: Path to the cache directory.
            check: Avoid writing any formatted files back; instead, exit with a
                non-zero status code if any files would have been modified, and zero
                otherwise.
            color: Control when colored output is used.
            config: Either a path to a TOML configuration file (`pyproject.toml` or
                `ruff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might
                find in a `ruff.toml` configuration file) overriding a specific
                configuration option (e.g., `--config "lint.line-length = 100"` or
                `--config "format.quote-style = 'single'"`). Overrides of individual
                settings using this option always take precedence over all
                configuration files, including configuration files that were also
                specified using `--config`.
            diff: Avoid writing any formatted files back; instead, exit with a
                non-zero status code and the difference between the current file and
                how the formatted file would look like.
            exclude: List of paths, used to omit files and/or directories from
                analysis.
            exit_non_zero_on_format: Exit with a non-zero status code if any files
                were modified via format, even if all files were formatted
                successfully.
            extend_exclude: Like --exclude, but adds additional files and
                directories on top of those already excluded.
            extension: List of mappings from file extension to language (one of
                `python`, `ipynb`, `pyi`). For example, to treat `.ipy` files as
                IPython notebooks, use `--extension ipy:ipynb`.
            force_exclude: Enforce exclusions, even for paths passed to Ruff
                directly on the command-line. Use `--no-force-exclude` to disable.
                `force_exclude=off` emits `--no-force-exclude`.
            isolated: Ignore all configuration files.
            line_length: Set the line-length.
            no_cache: Disable cache reads.
            output_format: Output serialization format for violations, when used
                with `--check`. The default serialization format is "full". Note
                that this option is currently only respected in preview mode. A
                warning will be emitted if this flag is used on stable.
            preview: Enable preview mode; enables unstable formatting. Use
                `--no-preview` to disable. `preview=off` emits `--no-preview`.
            quiet: Print diagnostics, but nothing else.
            range: When specified, Ruff will try to only format the code in the
                given range. It might be necessary to extend the start backwards or
                the end forwards, to fully enclose a logical line. The `<RANGE>`
                uses the format
                `<start_line>:<start_column>-<end_line>:<end_column>`. - The line
                and column numbers are 1 based. - The column specifies the
                nth-unicode codepoint on that line. - The end offset is exclusive. -
                The column numbers are optional. You can write `--range=1-2` instead
                of `--range=1:1-2:1`. - The end position is optional. You can write
                `--range=2` to format the entire document starting from the second
                line. - The start position is optional. You can write `--range=-3`
                to format the first three lines of the document. The option can only
                be used when formatting a single file. Range formatting of notebooks
                is unsupported.
            respect_gitignore: Respect file exclusions via `.gitignore` and other
                standard ignore files. Use `--no-respect-gitignore` to disable.
                `respect_gitignore=off` emits `--no-respect-gitignore`.
            silent: Disable all logging (but still exit with status code "1" upon
                detecting diagnostics).
            stdin_filename: The name of the file when passing it through stdin.
            target_version: The minimum Python version that should be supported.
            verbose: Enable verbose logging.
        """
        ...
