# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from ssh 10.4p1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result as _Result
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

class Ssh(_Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        A: _Flag = ...,
        B: _Value = ...,
        C: _Flag = ...,
        D: _Value = ...,
        E: _Value = ...,
        F: _Value = ...,
        G: _Flag = ...,
        I: _Value = ...,
        J: _Value = ...,
        K: _Flag = ...,
        L: _Value = ...,
        M: _Flag = ...,
        N: _Flag = ...,
        O: _Value = ...,
        P: _Value = ...,
        Q: _Value = ...,
        R: _Value = ...,
        S: _Value = ...,
        T: _Flag = ...,
        V: _Flag = ...,
        W: _Value = ...,
        X: _Flag = ...,
        Y: _Flag = ...,
        a: _Flag = ...,
        b: _Value = ...,
        c: _Value = ...,
        e: _Value = ...,
        f: _Flag = ...,
        g: _Flag = ...,
        i: _Value = ...,
        k: _Flag = ...,
        l: _Value = ...,
        m: _Value = ...,
        n: _Flag = ...,
        o: _Value = ...,
        p: _Value = ...,
        q: _Flag = ...,
        s: _Flag = ...,
        t: _Flag = ...,
        v: _Flag = ...,
        w: _Value = ...,
        x: _Flag = ...,
        y: _Flag = ...,
        **flags: Any,
    ) -> _Result:
        """SSH(1)                      General Commands Manual
        SSH(1)

        Args:
            A: Enables forwarding of connections from an authentication agent such
                as ssh-agent(1).
            B: Bind to the address of bind_interface before attempting to connect to
                the destination host.
            C: Requests compression of all data (including stdin, stdout, stderr,
                and data for forwarded X11, TCP and UNIX-domain connections).
            D: Specifies a local "dynamic" application-level port forwarding. May be
                repeated: a list emits the flag once per item.
            E: Append debug logs to log_file instead of standard error.
            F: Specifies an alternative per-user configuration file.
            G: Causes ssh to print its configuration after evaluating Host and Match
                blocks and exit.
            I: Specify the PKCS#11 shared library ssh should use to communicate with
                a PKCS#11 token providing keys for user authentication.
            J: Connect to the target host by first making an ssh connection to the
                jump host described by destination and then establishing a TCP
                forwarding to the ultimate destination from there. May be repeated:
                a list emits the flag once per item.
            K: Enables GSSAPI-based authentication and forwarding (delegation) of
                GSSAPI credentials to the server.
            L: Specifies that connections to the given TCP port or Unix socket on
                the local (client) host are to be forwarded to the given host and
                port, or Unix socket, on the remote side.
            M: Places the ssh client into "master" mode for connection sharing.
            N: Do not execute a remote command.
            O: Control an active connection multiplexing master process.
            P: Specify a tag name that may be used to select configuration in
                ssh_config(5). May be repeated: a list emits the flag once per item.
            Q: Queries for the algorithms supported by one of the following
                features: cipher (supported symmetric ciphers), cipher-auth
                (supported symmetric ciphers that support authenticated encryption),
                help (supported query terms for use with the -Q flag), mac
                (supported message integrity codes), kex (key exchange algorithms),
                key (key types), key-ca-sign (valid CA signature algorithms for
                certificates), key-cert (certificate key types), key-plain
                (non-certificate key types), key-sig (all key types and signature
                algorithms), protocol-version (supported SSH protocol versions), and
                sig (supported signature algorithms). May be repeated: a list emits
                the flag once per item.
            R: Specifies that connections to the given TCP port or Unix socket on
                the remote (server) host are to be forwarded to the local side.
            S: Specifies the location of a control socket for connection sharing, or
                the string "none" to disable connection sharing.
            T: Disable pseudo-terminal allocation.
            V: Display the version number and exit.
            W: Requests that standard input and output on the client be forwarded to
                host on port over the secure channel.
            X: Enables X11 forwarding.
            Y: Enables trusted X11 forwarding.
            a: Disables forwarding of the authentication agent connection.
            b: Use bind_address on the local machine as the source address of the
                connection.
            c: Selects the cipher specification for encrypting the session.
            e: Sets the escape character for sessions with a pty . Defaults to `~`.
            f: Requests ssh to go to background just before command execution.
            g: Allows remote hosts to connect to local forwarded ports.
            i: Selects a file from which the identity (private key) for public key
                authentication is read.
            k: Disables forwarding (delegation) of GSSAPI credentials to the server.
            l: Specifies the user to log in as on the remote machine. May be
                repeated: a list emits the flag once per item.
            m: A comma-separated list of MAC (message authentication code)
                algorithms, specified in order of preference.
            n: Redirects stdin from /dev/null (actually, prevents reading from
                stdin).
            o: Can be used to give options in the format used in the configuration
                file. May be repeated: a list emits the flag once per item.
            p: Port to connect to on the remote host. May be repeated: a list emits
                the flag once per item.
            q: Quiet mode.
            s: May be used to request invocation of a subsystem on the remote
                system.
            t: Force pseudo-terminal allocation.
            v: Verbose mode.
            w: Requests tunnel device forwarding with the specified tun(4) devices
                between the client (local_tun) and the server (remote_tun). May be
                repeated: a list emits the flag once per item.
            x: Disables X11 forwarding.
            y: Send log information using the syslog(3) system module.
        """
        ...
