# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from ssh-keyscan 10.4p1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result as _Result
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

class SshKeyscan(_Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        D: _Flag = ...,
        H: _Flag = ...,
        O: _Value = ...,
        T: _Value = ...,
        c: _Flag = ...,
        f: _Value = ...,
        p: _Value = ...,
        q: _Flag = ...,
        t: _Value = ...,
        v: _Flag = ...,
        **flags: Any,
    ) -> _Result:
        """SSH-KEYSCAN(1)              General Commands Manual
        SSH-KEYSCAN(1)

        Args:
            D: Print keys found as SSHFP DNS records.
            H: Hash all hostnames and addresses in the output.
            O: Specify a key/value option.
            T: Set the timeout for connection attempts.
            c: Request certificates from target hosts instead of plain keys.
            f: Read hosts or "addrlist namelist" pairs from file, one per line.
            p: Connect to port on the remote host.
            q: Quiet mode: do not print server host name and banners in comments.
            t: Specify the type of the key to fetch from the scanned hosts. May be
                repeated: a list emits the flag once per item.
            v: Verbose mode: print debugging messages about progress.
        """
        ...
