# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from ssh-keygen 10.4p1 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result as _Result
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

class SshKeygen(_Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        A: _Flag = ...,
        B: _Flag = ...,
        C: _Value = ...,
        D: _Value = ...,
        E: _Value = ...,
        F: _Flag = ...,
        H: _Flag = ...,
        I: _Value = ...,
        K: _Flag = ...,
        L: _Flag = ...,
        M: _Value = ...,
        N: _Value = ...,
        O: _Value = ...,
        P: _Value = ...,
        Q: _Flag = ...,
        R: _Flag = ...,
        U: _Flag = ...,
        V: _Value = ...,
        Y: _Value = ...,
        Z: _Value = ...,
        a: _Value = ...,
        b: _Value = ...,
        c: _Flag = ...,
        e: _Flag = ...,
        f: _Value = ...,
        g: _Flag = ...,
        h: _Flag = ...,
        i: _Flag = ...,
        k: _Flag = ...,
        l: _Flag = ...,
        m: _Value = ...,
        n: _Value = ...,
        p: _Flag = ...,
        q: _Flag = ...,
        r: _Value = ...,
        s: _Value = ...,
        t: _Flag = ...,
        u: _Flag = ...,
        v: _Flag = ...,
        w: _Value = ...,
        y: _Flag = ...,
        z: _Value = ...,
        **flags: Any,
    ) -> _Result:
        """SSH-KEYGEN(1)               General Commands Manual
        SSH-KEYGEN(1)

        Args:
            A: Generate host keys of all default key types (rsa, ecdsa,
                mldsa44-ed25519 and ed25519) if they do not already exist.
            B: Show the bubblebabble digest of specified private or public key file.
            C: Provides a new comment.
            D: Download the public keys provided by the PKCS#11 shared library
                pkcs11.
            E: Specifies the hash algorithm used when displaying key fingerprints.
            F: Search for the specified hostname (with optional port number) in a
                known_hosts file, listing any occurrences found.
            H: Hash a known_hosts file.
            I: Specify the key identity when signing a public key.
            K: Download resident keys from a FIDO authenticator.
            L: Prints the contents of one or more certificates.
            M: Generate candidate Diffie-Hellman Group Exchange (DH-GEX) parameters
                for eventual use by the 'diffie-hellman-group-exchange-*' key
                exchange methods.
            N: Provides the new passphrase.
            O: Specify a key/value option. May be repeated: a list emits the flag
                once per item.
            P: Provides the (old) passphrase.
            Q: Test whether keys have been revoked in a KRL.
            R: Removes all keys belonging to the specified hostname (with optional
                port number) from a known_hosts file.
            U: When used in combination with -s or -Y sign, this option indicates
                that a CA key resides in an ssh-agent(1).
            V: Specify a validity interval when signing a certificate. May be
                repeated: a list emits the flag once per item.
            Y: Find the principal(s) associated with the public key of a signature,
                provided using the -s flag in an authorized signers file provided
                using the -f flag.
            Z: Specifies the cipher to use for encryption when writing an
                OpenSSH-format private key file.
            a: When saving a private key, this option specifies the number of KDF
                (key derivation function, currently bcrypt_pbkdf(3)) rounds used.
            b: Specifies the number of bits in the key to create.
            c: Requests changing the comment in the private and public key files.
            e: This option will read a private or public OpenSSH key file and print
                to stdout a public key in one of the formats specified by the -m
                option.
            f: Specifies the filename of the key file.
            g: Use generic DNS format when printing fingerprint resource records
                using the -r command.
            h: When signing a key, create a host certificate instead of a user
                certificate.
            i: This option will read an unencrypted private (or public) key file in
                the format specified by the -m option and print an OpenSSH
                compatible private (or public) key to stdout.
            k: Generate a KRL file.
            l: Show fingerprint of specified public key file.
            m: Specify a key format for key generation, the -i (import), -e (export)
                conversion options, and the -p change passphrase operation. May be
                repeated: a list emits the flag once per item.
            n: Specify one or more principals (user or host names) to be included in
                a certificate when signing a key. May be repeated: a list emits the
                flag once per item.
            p: Requests changing the passphrase of a private key file instead of
                creating a new private key.
            q: Silence ssh-keygen.
            r: Print the SSHFP fingerprint resource record named hostname for the
                specified public key file.
            s: Certify (sign) a public key using the specified CA key.
            t: Specifies the type of key to create.
            u: Update a KRL.
            v: Verbose mode.
            w: Specifies a path to a library that will be used when creating FIDO
                authenticator-hosted keys, overriding the default of using the
                internal USB HID support.
            y: This option will read a private OpenSSH format file and print an
                OpenSSH public key to stdout.
            z: Specifies a serial number to be embedded in the certificate to
                distinguish this certificate from others from the same CA.
        """
        ...
