# Generated by `fm tools.sync` — do not edit by hand.
#
# Read from tea 0.15.0 on Windows. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any, Self

from footman.tools import Result as _Result
from footman.tools import Tool as _Tool
from footman.tools import _Flag, _Value

class Tea(_Tool):
    class Branches(_Tool):
        def list(
            self,
            *,
            debug: _Flag = ...,
            fields: _Value = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                fields: Comma-separated list of fields to print. Defaults to
                    `name,protected,user-can-merge,user-can-push`.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    branches: Branches
    class Comments(_Tool):
        def add(
            self,
            issue: str,
            /,
            *args: str,
            debug: _Flag = ...,
            description: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                description: comment body (alternative to the positional argument).
                login: Use a different Gitea Login.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def list(
            self,
            issue: str,
            /,
            *args: str,
            debug: _Flag = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    comments: Comments
    class Issues(_Tool):
        def close(
            self,
            issue: str,
            /,
            *args: str,
            debug: _Flag = ...,
            login: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                login: Use a different Gitea Login.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def create(
            self,
            *,
            assignees: _Value = ...,
            deadline: _Value = ...,
            debug: _Flag = ...,
            description: _Value = ...,
            labels: _Value = ...,
            login: _Value = ...,
            milestone: _Value = ...,
            referenced_version: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            title: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                assignees: Comma-separated list of usernames to assign.
                deadline: Deadline timestamp to assign.
                debug: Enable debug mode.
                labels: Comma-separated list of labels to assign.
                login: Use a different Gitea Login.
                milestone: Milestone to assign.
                referenced_version: commit-hash or tag name to assign.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def list(
            self,
            *,
            assignee: _Value = ...,
            author: _Value = ...,
            debug: _Flag = ...,
            fields: _Value = ...,
            from_: _Value = ...,
            keyword: _Value = ...,
            kind: _Value = ...,
            labels: _Value = ...,
            limit: _Value = ...,
            login: _Value = ...,
            mentions: _Value = ...,
            milestones: _Value = ...,
            output: _Value = ...,
            owner: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            state: _Value = ...,
            until: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                fields: Comma-separated list of fields to print. Defaults to
                    `index,title,state,author,milestone,labels,owner,repo`.
                from_: Filter by activity after this date.
                keyword: Filter by search string.
                kind: Whether to return issues, `pulls`, or `all` (you can use this
                    to apply advanced search filters to PRs). Defaults to `issues`.
                labels: Comma-separated list of labels to match issues against.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                milestones: Comma-separated list of milestones to match issues
                    against.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                state: Filter by state (all|open|closed). Defaults to `open`.
                until: Filter by activity before this date.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    issues: Issues
    class Labels(_Tool):
        def create(
            self,
            *,
            color: _Value = ...,
            debug: _Flag = ...,
            description: _Value = ...,
            file: _Value = ...,
            login: _Value = ...,
            name: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                color: label color value.
                debug: Enable debug mode.
                description: label description.
                file: indicate a label file.
                login: Use a different Gitea Login.
                name: label name.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            exclude_org: _Flag = ...,
            limit: _Value = ...,
            login: _Value = ...,
            org: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            save: _Flag = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                exclude_org: Exclude organization labels from the list.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                org: List organization labels.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                save: Save all the labels as a file.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    labels: Labels
    class Logins(_Tool):
        def add(
            self,
            *,
            client_id: _Value = ...,
            debug: _Flag = ...,
            git_credentials: _Flag = ...,
            insecure: _Flag = ...,
            name: _Value = ...,
            no_version_check: _Flag = ...,
            oauth: _Flag = ...,
            otp: _Value = ...,
            password: _Value = ...,
            redirect_url: _Value = ...,
            scopes: _Value = ...,
            ssh_agent_key: _Value = ...,
            ssh_agent_principal: _Value = ...,
            ssh_key: _Value = ...,
            token: _Value = ...,
            url: _Value = ...,
            user: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                client_id: OAuth client ID (for use with --oauth).
                debug: Enable debug mode.
                git_credentials: Register tea as a git credential helper for this
                    login's URL, so 'git push' and 'git clone' over HTTPS
                    authenticate silently using the stored token.
                insecure: Disable TLS verification.
                name: Login name.
                no_version_check: Do not check version of Gitea instance.
                oauth: Use interactive OAuth2 flow for authentication.
                otp: OTP token for auth, if necessary [%GITEA_SERVER_OTP%].
                password: Password for basic auth (will create token)
                    [%GITEA_SERVER_PASSWORD%].
                redirect_url: OAuth redirect URL (for use with --oauth).
                scopes: Token scopes to add when creating a new token, separated by
                    a comma [%GITEA_SCOPES%].
                ssh_agent_key: Use SSH public key or SSH fingerprint to login (needs
                    a running ssh-agent with ssh key loaded).
                ssh_agent_principal: Use SSH certificate with specified principal to
                    login (needs a running ssh-agent with certificate loaded).
                ssh_key: Path to a SSH key/certificate to use, overrides
                    auto-discovery.
                token: Access token.
                url: Server URL [%GITEA_SERVER_URL%]. Defaults to
                    `https://gitea.com`.
                user: User for basic auth (will create token) [%GITEA_SERVER_USER%].
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            output: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                output: Output format.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    logins: Logins
    class Milestones(_Tool):
        def create(
            self,
            *,
            deadline: _Value = ...,
            debug: _Flag = ...,
            description: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            state: _Value = ...,
            title: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                deadline: set milestone deadline. Defaults to `is no due date`.
                debug: Enable debug mode.
                description: milestone description to create.
                login: Use a different Gitea Login.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                state: set milestone state. Defaults to `is open`.
                title: milestone title to create.
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            fields: _Value = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            state: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                fields: Comma-separated list of fields to print. Defaults to
                    `title,items,duedate`.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                state: Filter by milestone state (all|open|closed). Defaults to
                    `open`.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    milestones: Milestones
    class Pulls(_Tool):
        def checkout(
            self,
            pull: str,
            /,
            *args: str,
            branch: _Flag = ...,
            debug: _Flag = ...,
            login: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                branch: Create a local branch if it doesn't exist yet.
                debug: Enable debug mode.
                login: Use a different Gitea Login.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def create(
            self,
            *,
            agit: _Flag = ...,
            allow_maintainer_edits: _Flag = ...,
            assignees: _Value = ...,
            base: _Value = ...,
            deadline: _Value = ...,
            debug: _Flag = ...,
            description: _Value = ...,
            draft: _Flag = ...,
            head: _Value = ...,
            labels: _Value = ...,
            login: _Value = ...,
            milestone: _Value = ...,
            referenced_version: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            title: _Value = ...,
            topic: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                agit: Create an agit flow pull request.
                allow_maintainer_edits: Enable maintainers to push to the base
                    branch of created pull.
                assignees: Comma-separated list of usernames to assign.
                base: Branch name of the PR target. Defaults to `is repos default
                    branch`.
                deadline: Deadline timestamp to assign.
                debug: Enable debug mode.
                draft: Create as a draft (prepends "WIP: " to the title; Gitea
                    treats WIP-prefixed PRs as drafts).
                head: Branch name of the PR source . Defaults to `is current one`.
                labels: Comma-separated list of labels to assign.
                login: Use a different Gitea Login.
                milestone: Milestone to assign.
                referenced_version: commit-hash or tag name to assign.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                topic: Topic name for agit flow pull request.
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            fields: _Value = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            state: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                fields: Comma-separated list of fields to print. Defaults to
                    `index,title,state,author,milestone,updated,labels`.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                state: Filter by state (all|open|closed). Defaults to `open`.
            """
            ...
        def merge(
            self,
            pull: str,
            /,
            *args: str,
            debug: _Flag = ...,
            login: _Value = ...,
            message: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            style: _Value = ...,
            title: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                login: Use a different Gitea Login.
                message: Merge commit message.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                style: Kind of merge to perform: merge, rebase, squash,
                    rebase-merge. Defaults to `merge`.
                title: Merge commit title.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    pulls: Pulls
    class Releases(_Tool):
        def assets(
            self,
            *args: str,
            debug: _Flag = ...,
            login: _Value = ...,
            output: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                login: Use a different Gitea Login.
                output: Output format.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def create(
            self,
            *args: str,
            asset: _Value = ...,
            debug: _Flag = ...,
            draft: _Flag = ...,
            login: _Value = ...,
            note: _Value = ...,
            note_file: _Value = ...,
            output: _Value = ...,
            prerelease: _Flag = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            tag: _Value = ...,
            target: _Value = ...,
            title: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                asset: Path to file attachment. May be repeated: a list emits the
                    flag once per item.
                debug: Enable debug mode.
                draft: Is a draft.
                login: Use a different Gitea Login.
                note: Release notes.
                note_file: Release notes file name.
                output: Output format.
                prerelease: Is a pre-release.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
                tag: Tag name.
                target: Target branch name or commit hash.
                title: Release title.
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            page: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                page: specify page. Defaults to `1`.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    releases: Releases
    class Repos(_Tool):
        def create(
            self,
            *,
            branch: _Value = ...,
            debug: _Flag = ...,
            description: _Value = ...,
            gitignores: _Value = ...,
            init: _Flag = ...,
            labels: _Value = ...,
            license: _Value = ...,
            login: _Value = ...,
            name: _Value = ...,
            object_format: _Value = ...,
            output: _Value = ...,
            owner: _Value = ...,
            private: _Flag = ...,
            readme: _Value = ...,
            template: _Flag = ...,
            trustmodel: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                branch: use custom default branch (need --init).
                debug: Enable debug mode.
                description: add description to repo.
                gitignores: list of gitignore templates (need --init).
                init: initialize repo.
                labels: name of label set to add.
                license: add license (need --init).
                login: Use a different Gitea Login.
                name: name of new repo.
                object_format: select git object format (sha1,sha256).
                output: Output format.
                owner: name of repo owner.
                private: make repo private.
                readme: use readme template (need --init).
                template: make repo a template repo.
                trustmodel: select trust model
                    (committer,collaborator,collaborator+committer).
            """
            ...
        def fork(
            self,
            *,
            debug: _Flag = ...,
            login: _Value = ...,
            owner: _Value = ...,
            remote: _Value = ...,
            repo: _Value = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                login: Use a different Gitea Login.
                owner: name of fork's owner, defaults to current user.
                remote: Discover Gitea login from remote.
                repo: Override local repository path or gitea repository slug to
                    interact with.
            """
            ...
        def list(
            self,
            *,
            debug: _Flag = ...,
            fields: _Value = ...,
            limit: _Value = ...,
            login: _Value = ...,
            output: _Value = ...,
            owner: _Value = ...,
            page: _Value = ...,
            starred: _Flag = ...,
            type: _Value = ...,
            watched: _Flag = ...,
            **flags: Any,
        ) -> _Result:
            """Run this verb.

            Args:
                debug: Enable debug mode.
                fields: Comma-separated list of fields to print. Defaults to
                    `owner,name,type,ssh`.
                limit: specify limit of items per page. Defaults to `30`.
                login: Use a different Gitea Login.
                output: Output format.
                owner: List repos of a specific owner (org or user).
                page: specify page. Defaults to `1`.
                starred: List your starred repos instead.
                type: Filter by type: fork, mirror, source.
                watched: List your watched repos instead.
            """
            ...
        def flags(
            self,
            **flags: Any,
        ) -> Self:
            """Bind tool-level global options before the subcommand.

            `tools.docker.flags(host=...)` puts a tool's own
            options ahead of the verb, where they belong."""
            ...

    repos: Repos
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        debug: _Flag = ...,
        **flags: Any,
    ) -> _Result:
        """Run this verb.

        Args:
            debug: Enable debug mode.
        """
        ...
    def api(
        self,
        endpoint: str,
        /,
        *args: str,
        Field: _Value = ...,
        data: _Value = ...,
        debug: _Flag = ...,
        field: _Value = ...,
        header: _Value = ...,
        include: _Flag = ...,
        login: _Value = ...,
        method: _Value = ...,
        output: _Value = ...,
        remote: _Value = ...,
        repo: _Value = ...,
        **flags: Any,
    ) -> _Result:
        """Run this verb.

        Args:
            Field: Add a typed field to the request body (key=value, @file, or @-
                for stdin).
            data: Raw JSON request body (use @file to read from file, @- for stdin).
            debug: Enable debug mode.
            field: Add a string field to the request body (key=value).
            header: Add a custom header (key:value).
            include: Include HTTP status and response headers in output (written to
                stderr).
            login: Use a different Gitea Login.
            method: HTTP method (GET, POST, PUT, PATCH, DELETE). Defaults to `GET`.
            output: Write response body to file instead of stdout (use '-' for
                stdout).
            remote: Discover Gitea login from remote.
            repo: Override local repository path or gitea repository slug to
                interact with.
        """
        ...
    def clone(
        self,
        repo_slug: str,
        /,
        *args: str,
        debug: _Flag = ...,
        depth: _Value = ...,
        login: _Value = ...,
        **flags: Any,
    ) -> _Result:
        """Run this verb.

        Args:
            debug: Enable debug mode.
            depth: num commits to fetch, defaults to all. Defaults to `0`.
            login: Use a different Gitea Login.
        """
        ...
    def whoami(
        self,
        *,
        debug: _Flag = ...,
        **flags: Any,
    ) -> _Result:
        """Run this verb.

        Args:
            debug: Enable debug mode.
        """
        ...
    def flags(
        self,
        *,
        debug: _Flag = ...,
        **flags: Any,
    ) -> Self:
        """Bind tool-level global options before the subcommand.

        `tools.docker.flags(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
