# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from twine 6.2.0 on macOS. In-process: no.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Result, Tool, _Flag, _Value

class Twine(Tool):
    def __call__(  # type: ignore[override]
        self,
        *args: str,
        no_color: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> Result:
        """Run this verb.

        Args:
            no_color: disable colored output.
        """
        ...
    def check(
        self,
        dist: str,
        /,
        *args: str,
        strict: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> Result:
        """Run this verb.

        Args:
            strict: Fail on warnings.
        """
        ...
    def upload(
        self,
        dist: str,
        /,
        *args: str,
        attestations: _Flag = ...,
        cert: _Value = ...,
        client_cert: _Value = ...,
        comment: _Value = ...,
        config_file: _Value = ...,
        disable_progress_bar: _Flag = ...,
        identity: _Value = ...,
        non_interactive: _Flag = ...,
        password: _Value = ...,
        repository: _Value = ...,
        repository_url: _Value = ...,
        sign: _Flag = ...,
        sign_with: _Value = ...,
        skip_existing: _Flag = ...,
        username: _Value = ...,
        verbose: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> Result:
        """[--config-file CONFIG_FILE] [--skip-existing] [--cert path] [--client-cert
        path] [--verbose] [--disable-progress-bar]

        Args:
            attestations: Upload each file's associated attestations.
            cert: Path to alternate CA bundle (can also be set via TWINE_CERT
                environment variable).
            client_cert: Path to SSL client certificate, a single file containing
                the private key and the certificate in PEM format.
            comment: The comment to include with the distribution file.
            config_file: The .pypirc config file to use.
            disable_progress_bar: Disable the progress bar.
            identity: GPG identity used to sign files.
            non_interactive: Do not interactively prompt for username/password if
                the required credentials are missing.
            password: The password to authenticate to the repository (package index)
                with.
            repository: The repository (package index) to upload the package to.
                Defaults to `pypi`.
            repository_url: The repository (package index) URL to upload the package
                to.
            sign: Sign files to upload using GPG.
            sign_with: GPG program used to sign uploads. Defaults to `gpg`.
            skip_existing: Continue uploading files if one already exists.
            username: The username to authenticate to the repository (package index)
                as.
            verbose: Show verbose output.
        """
        ...
    def opts(
        self,
        *,
        no_color: _Flag = ...,
        **flags: Any,
    ) -> Twine:
        """Bind tool-level global options before the subcommand.

        `tools.docker.opts(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
