# Generated by `fm footman tools sync` — do not edit by hand.
#
# Read from zensical 0.0.50 on macOS. In-process: default.
# Every verb ends in `**flags: Any`: the stub suggests what this tool
# accepts, and can never forbid what the bridge would happily pass.
from typing import Any

from footman.tools import Tool, _Flag, _Value

class _Zensical(Tool):
    def build(
        self,
        *,
        clean: _Flag = ...,
        config_file: _Value = ...,
        strict: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Build a project.

        Args:
            clean: Clean cache.
            config_file: Path to config file.
            strict: Enable strict mode - abort the build on warnings.
        """
        ...
    def new(
        self,
        *args: str,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Create a new template project in the current or given directory."""
        ...
    def serve(
        self,
        *,
        config_file: _Value = ...,
        dev_addr: _Value = ...,
        open: _Flag = ...,
        strict: _Flag = ...,
        nofail: bool = False,
        in_process: bool | None = None,
        **flags: Any,
    ) -> int:
        """Build and serve a project.

        Args:
            config_file: Path to config file.
            dev_addr: IP address and port (default: localhost:8000).
            open: Open preview in default browser.
            strict: Strict mode (currently unsupported).
        """
        ...
    def opts(
        self,
        **flags: Any,
    ) -> _Zensical:
        """Bind tool-level global options before the subcommand.

        `tools.docker.opts(host=...)` puts a tool's own
        options ahead of the verb, where they belong."""
        ...
